// Conteúdo de estudo da matéria Pesquisa, Tecnologia e Inovação.
// Gerado a partir dos arquivos desta pasta (livros-texto e slides das Unidades I a IV).
registrarMateria({
  nome: "Pesquisa, Tecnologia e Inovação",
  descricao: "Conhecimento e método científico, tipos de pesquisa, trabalhos acadêmicos, estrutura da monografia (ABNT), citações e referências, plágio e inovações que nasceram da pesquisa científica.",
  arquivos: [
    "Livro Texto - Unidade I.pdf",
    "Livro Texto - Unidade II.pdf",
    "Livro Texto - Unidade III.pdf",
    "Livro Texto - Unidade IV.pdf",
    "Slide de Aula - Unidade I.pdf",
    "Slide de Aula - Unidade II.pdf",
    "Slide de Aula - Unidade III.pdf",
    "Slide de Aula - Unidade IV.pdf",
  ],

  // ------------------------------------------------------------------
  resumo: {
    titulo: "Pesquisa, Tecnologia e Inovação — Unidades I a IV",
    secoes: [
      {
        titulo: "Conhecimento e ciência",
        paragrafos: [
          "Conhecimento é a percepção ou a compreensão de algo, obtida por meio da experiência, da reflexão, da prática ou do estudo. Outros animais também ensinam estratégias de sobrevivência aos descendentes, mas o ser humano registra o conhecimento por meio de símbolos (escrita, gravação, filmagem), o que permite acumulá-lo e transmiti-lo de geração em geração. Isso é essencial para a evolução da humanidade.",
          "A palavra “ciência” vem do latim scientia, que significa conhecimento, mas os termos não são sinônimos. A ciência é um grande empreendimento coletivo que organiza nossos conhecimentos e previsões sobre o universo, obtidos, confrontados e atualizados por um método próprio e transparente, que reduz as incertezas sobre a realidade. Ela funciona como um “par de óculos” que dá nitidez à nossa visão do mundo e se baseia em regras universais, de modo que quem não participou da produção do conhecimento consegue compreendê-lo e usá-lo.",
          "Os slides também diferenciam, no contexto da gestão do conhecimento, o conhecimento tácito, internalizado nas pessoas e adquirido pela experiência, pela prática e pela intuição (difícil de formalizar, documentar e transmitir, como a habilidade motora de um cirurgião), do conhecimento explícito, que pode ser facilmente codificado em livros, manuais e documentos.",
        ],
      },
      {
        titulo: "Tipos de conhecimento",
        paragrafos: [
          "O conhecimento pode ser pensado a partir de quatro tipos principais: popular, filosófico, teológico e científico.",
          "O conhecimento popular (senso comum, também chamado de empírico) é adquirido de forma espontânea, no trato direto com as coisas e as pessoas, sem método e sem reflexão profunda. Exemplo: o avô que ensina o neto a fazer pão “até a massa dobrar de tamanho”, sem explicar a fermentação. É tradicionalmente aceito, mas pode ou não estar correto, como o mito de que leite com manga faz mal.",
          "O conhecimento filosófico usa a razão para questionar problemas humanos e discernir entre certo e errado, com reflexão racional, argumentação lógica e perguntas muitas vezes sem resposta definitiva (o que é a verdade? há sentido para a vida?). O debate entre Joana e Teresa sobre se mentir é eticamente aceitável é o exemplo do material: elas não chegam a um acordo, mas aprofundam a compreensão.",
          "O conhecimento teológico (religioso) trata de aspectos transcendentais, espirituais e sagrados e depende da fé em dogmas, afirmações aceitas como verdadeiras, incontestáveis e imutáveis, sustentadas por textos sagrados e experiências espirituais. Não é universal: varia de uma religião para outra.",
          "O conhecimento científico se fundamenta em métodos sistemáticos e rigorosos para investigar fenômenos naturais e sociais, buscando ser o mais imparcial possível, ou seja, minimizar os vieses pessoais dos pesquisadores. Ele começa com uma pergunta ou um problema, como no caso da engenheira Márcia, que observou falhas de corrosão em oleodutos, revisou a literatura, formulou uma hipótese (um novo composto polimérico), testou em laboratório, validou estatisticamente, repetiu os testes em condições reais e publicou os resultados em um periódico.",
        ],
        topicos: [
          "Popular — superficialidade (“porque eu vi”, “porque me disseram”), sensitividade (experiências vividas, emoções) e subjetividade (a própria pessoa organiza seus saberes, sem método).",
          "Científico — factualidade (lida com fatos, observações e medições), contingência (a veracidade das hipóteses é conhecida pela experimentação, e não apenas pela razão, como no filosófico), sistematicidade (saber ordenado logicamente), verificabilidade (o que não pode ser comprovado, como dogmas, não é ciência) e falibilidade (suas hipóteses não são incontestáveis nem imutáveis).",
          "Hipótese × dogma: a hipótese está sempre sujeita a testes e à refutação; o dogma é aceito sem questionamento.",
        ],
      },
      {
        titulo: "Raciocínio dedutivo e raciocínio indutivo",
        paragrafos: [
          "O raciocínio dedutivo parte de premissas gerais para chegar a conclusões específicas. Se as premissas forem verdadeiras e o raciocínio for válido, a conclusão é necessariamente verdadeira. Está associado à lógica formal e à matemática. Exemplo clássico: todo homem é mortal; Sócrates é um homem; portanto, Sócrates é mortal.",
          "O raciocínio indutivo parte de premissas específicas para chegar a conclusões gerais, e a conclusão deriva das premissas por probabilidade. Exemplo: o remédio R curou a doença D nos pacientes A, B, C, D e E; portanto, R cura D. Quanto mais premissas apoiam a conclusão, mais forte é o argumento. Premissa é a afirmação assumida como verdadeira que serve de base ao raciocínio.",
          "Os dois raciocínios são complementares: a indução gera premissas que servem de base para novas deduções. A indução é essencial para formular hipóteses e leis; a dedução é essencial para testar hipóteses, aplicar leis e validar teorias.",
        ],
      },
      {
        titulo: "Hipótese, lei e teoria",
        paragrafos: [
          "Hipótese é uma proposição formulada como possível solução para um problema ou possível explicação para um fenômeno. É o ponto de partida da investigação e ainda precisa ser testada.",
          "Lei científica é uma descrição precisa de um padrão ou comportamento observado na natureza: diz o que acontece, mas não explica por quê. Costuma ser expressa matematicamente. A física é a ciência que mais formula leis; as ciências sociais raramente produzem leis, pela complexidade do comportamento humano.",
          "Teoria científica é uma explicação abrangente e bem fundamentada para um conjunto de fenômenos: explica por que e como eles ocorrem, integra leis, hipóteses e evidências e faz previsões testáveis. Não deve ser confundida com o uso popular da palavra (“minha teoria é que ele esqueceu o celular”), que na verdade é uma hipótese.",
          "No exemplo fictício do inseto Aedes rapidus, a hipótese foi “se a temperatura aumentar, a velocidade aumentará”; a função v = 0,4·T − 2 (até 40 °C), completada por outro grupo e corroborada mundialmente, virou a “lei de rapidus”; e a explicação pela taxa metabólica e pelo estresse térmico acima de 40 °C é a teoria.",
        ],
      },
      {
        titulo: "Método científico",
        paragrafos: [
          "O método científico é o “roteiro” rigoroso que organiza as técnicas da ciência, e é ele que diferencia o conhecimento científico dos demais. Suas etapas: observação de fatos (que não são autoexplicativos), pesquisa bibliográfica (reunir o que já foi publicado), formulação de hipótese, verificação experimental (isolando variáveis em condições controladas) e, se a hipótese for confirmada, replicação dos resultados e consenso da comunidade, que podem transformá-la em lei. Várias leis podem se unificar em uma teoria, e várias teorias poderiam se resumir em um sistema, que ainda não foi estabelecido, mas é almejado pelos cientistas.",
          "Segundo Severino, o método se divide em duas fases. O método experimental, dominado pelo raciocínio indutivo, vai dos fatos às hipóteses gerais, que podem ou não virar leis. O método matemático, dominado pelo raciocínio dedutivo, parte das leis para hipóteses mais abrangentes que, confirmadas, viram teorias e podem levar a uma hipótese universal. As leis, portanto, são conclusões de um processo indutivo.",
        ],
      },
      {
        titulo: "Tipos de pesquisa",
        paragrafos: [
          "Embora o método científico seja universal, a forma de praticar a pesquisa varia, e as pesquisas podem ser classificadas de várias maneiras.",
          "Quanto à abordagem do problema: a pesquisa quantitativa usa dados numéricos e estatística (porcentagens, médias, correlações) para mensurar, testar hipóteses e generalizar, como o questionário fechado com 1000 estudantes sobre horas em redes sociais e notas. A qualitativa trabalha com dados não numéricos (textos, entrevistas, observações) para compreender significados, motivações e percepções, como as perguntas abertas a 50 estudantes. As duas podem ser combinadas em uma abordagem mista.",
          "Quanto à natureza: a pesquisa básica (pura) amplia o conhecimento sem se preocupar com aplicação imediata (ex.: como o cérebro armazena memórias de longo prazo); a aplicada resolve problemas específicos ou desenvolve tecnologias (ex.: um medicamento para Alzheimer) e costuma usar o conhecimento gerado pela básica.",
          "Quanto aos procedimentos técnicos, também chamados de metodologias de pesquisa, há os tipos listados abaixo.",
        ],
        topicos: [
          "Bibliográfica: revisão de materiais já publicados (livros, artigos, teses) para embasar o estudo ou revisar o estado da arte.",
          "Experimental: manipulação de variáveis em ambiente controlado, como um laboratório; comum nas ciências da natureza.",
          "De levantamento: coleta de dados por questionários ou entrevistas com uma amostra ou população.",
          "Documental: usa documentos oficiais, pessoais ou registros históricos como fonte; comum em pesquisas históricas, jurídicas e sociológicas.",
          "Estudo de caso: estudo aprofundado de uma situação específica (ex.: tratamento de um paciente com doença rara); pode combinar outros procedimentos.",
          "Pesquisa-ação: pesquisadores e pessoas afetadas pelo problema atuam de forma cooperativa para resolvê-lo (ex.: programa de gestão de resíduos envolvendo a comunidade escolar).",
        ],
      },
      {
        titulo: "Monografias e títulos acadêmicos",
        paragrafos: [
          "Trabalho acadêmico é uma produção de cunho científico desenvolvida no âmbito de uma instituição de ensino superior ou de pesquisa. Monografia é o trabalho acadêmico textual longo (dezenas ou centenas de páginas) que documenta o estudo de um tema específico, formatado conforme o guia de normalização da instituição, que segue as NBRs da ABNT. O livro adota a definição ampla: uma tese de doutorado também é uma monografia.",
          "Um TCC não é em si uma monografia: ele pode incluir a monografia, a apresentação para a banca (defesa) e, às vezes, protótipos. A monografia é a principal documentação exigida.",
          "Na graduação há três títulos: bacharel (formação generalista, como direito e engenharias), licenciado (forma educadores, como matemática e física) e tecnólogo (foco prático e técnico, como análise e desenvolvimento de sistemas).",
        ],
        topicos: [
          "Trabalho de graduação: feito ao longo do curso (ex.: projetos integrados multidisciplinares), geralmente em grupo, com tema definido pelos professores; algumas dezenas de páginas; inicia o aluno na pesquisa.",
          "TCC de graduação: ao fim do curso, comum em bacharelados e licenciaturas (nem sempre em cursos tecnológicos); monografia mais longa e defesa diante de banca; aprovado, costuma integrar a biblioteca da instituição.",
          "Especialização (lato sensu, “em sentido amplo”): foco na aplicação prática no mercado; confere o título de especialista; o trabalho de conclusão nem sempre é exigido.",
          "Dissertação de mestrado (stricto sensu, “em sentido restrito”): pesquisa aprofundada, domínio de idioma estrangeiro, referências vastas, defesa; não exige originalidade.",
          "Tese de doutorado: além das exigências do mestrado, exige contribuição inédita para a ciência (novas descobertas, novos métodos, refutação de hipóteses etc.), que não precisa ser revolucionária.",
        ],
      },
      {
        titulo: "Artigos científicos e comunicação científica",
        paragrafos: [
          "O artigo científico apresenta os resultados de uma pesquisa original, feita pelo método científico, e é a principal ferramenta de comunicação entre cientistas do mundo todo. É mais curto que uma monografia, mas denso. É publicado em periódicos (revistas científicas), depois de passar pela revisão por pares (peer review), em que especialistas da área avaliam qualidade, originalidade, validade e relevância. A maior parte dos artigos relevantes é publicada em inglês, idioma padrão da ciência.",
          "Além das publicações, os cientistas se encontram em eventos. O congresso reúne várias áreas ligadas a um tema geral, dura de três a cinco dias e tem palestras de convidados, apresentações orais (selecionadas por submissão), sessões de pôsteres e mesas-redondas. O simpósio tem tema mais delimitado e dura de um a cinco dias.",
          "A divulgação científica populariza a ciência para o público, com vocabulário mais simples. Para reconhecer fontes confiáveis: verificar quem publica (universidades, Fiocruz, Inpe, Nasa, CNPq, Nature, Science), identificar a autoria e o currículo, verificar se há referências e desconfiar de sensacionalismo, curas milagrosas e tom alarmista.",
        ],
        topicos: [
          "Estrutura do artigo: título; autores e afiliação; resumo (“miniatura” do artigo); palavras-chave (alimentam bases de dados).",
          "Introdução: contém a revisão bibliográfica e, geralmente no último parágrafo, o objetivo.",
          "Material e métodos: detalha materiais e procedimentos para que outros possam replicar o estudo.",
          "Resultados e discussão: apresenta resultados (tabelas, gráficos) e os interpreta, mostrando concordância ou discordância com a literatura.",
          "Conclusão (reúne as inferências e sugere estudos futuros), agradecimentos (inclusive a instituições de fomento) e referências (a maior parte das citações fica na introdução e na discussão).",
        ],
      },
      {
        titulo: "Estrutura da monografia: parte externa e elementos pré-textuais",
        paragrafos: [
          "Pela ABNT NBR 14724 (2024), a monografia tem uma parte externa e uma parte interna. A parte interna se divide em elementos pré-textuais, textuais e pós-textuais. Detalhes de aparência (fonte, margens, paginação) devem ser consultados no guia de normalização da instituição, que é baseado na ABNT mas pode ter particularidades.",
          "Na parte externa, a capa é obrigatória e traz instituição, autor, título, subtítulo (se houver), cidade e ano. A lombada é opcional: é a lateral perpendicular à capa, usada só em encadernação de capa dura; não existe em espiral nem em trabalhos digitais (NBR 12225).",
          "Os pré-textuais aparecem nesta ordem: folha de rosto (obrigatória), errata (opcional), folha de aprovação (obrigatória), dedicatória, agradecimentos e epígrafe (opcionais), resumo e resumo em língua estrangeira (obrigatórios), listas de ilustrações, tabelas, abreviaturas e siglas e símbolos (opcionais) e sumário (obrigatório).",
        ],
        topicos: [
          "Folha de rosto: repete a capa e acrescenta a natureza do trabalho (tipo, objetivo, instituição, área de concentração) e o orientador; no verso, a ficha catalográfica, feita pela biblioteca.",
          "Errata: só quando há erros identificados após a impressão; lista folha, linha e correção; vem logo após a folha de rosto.",
          "Folha de aprovação: data de aprovação, nome, titulação e assinatura da banca, preenchidas após a aprovação (muitas vezes não exigida em trabalhos de graduação).",
          "Dedicatória (homenagem, normalmente sem título), agradecimentos (de bom tom incluir) e epígrafe (citação curta ligada ao tema).",
          "Resumo (NBR 6028): escrito só depois da parte textual pronta; parágrafo único, sem tópicos, entre 150 e 500 palavras, sintetizando introdução, desenvolvimento e conclusão; ao final, pelo menos três palavras-chave separadas por ponto e vírgula e finalizadas por ponto.",
          "Resumo em língua estrangeira: o mesmo texto em outro idioma; em inglês, intitula-se Abstract e as palavras-chave são Keywords.",
          "Listas: ilustrações e tabelas seguem a ordem do texto, com número, legenda e página; abreviaturas e siglas seguem a ordem alfabética; símbolos seguem a ordem em que aparecem (útil em exatas).",
          "Sumário: enumera as seções com a mesma ordem e grafia do texto e as páginas; inclui a parte textual (numerada) e a pós-textual (sem numeração).",
        ],
      },
      {
        titulo: "Elementos textuais e pós-textuais",
        paragrafos: [
          "Os elementos textuais são três, todos obrigatórios: introdução, desenvolvimento e conclusão. A ABNT divide o trabalho em seções numeradas (1, 2.1, 2.2.1), e não em capítulos; a introdução é a seção 1.",
          "A introdução orienta a leitura e costuma trazer: contextualização (sobre o que é o trabalho), problema (situação a resolver, geralmente em forma de pergunta, que delimita o tema), hipótese (quando couber, a resposta que o autor imagina), justificativa (por que é importante resolver o problema; dá credibilidade), objetivo geral e objetivos específicos (etapas para atingir o geral, normalmente em tópicos), breve menção aos métodos e apresentação das próximas seções. Objetivos claros direcionam a pesquisa e delimitam o escopo.",
          "O desenvolvimento fica entre a introdução e a conclusão e detalha a pesquisa: referencial teórico, métodos e dados com análise e discussão. Em uma dissertação, por exemplo: 2 Revisão da literatura (embasamento teórico), 3 Materiais e métodos (permite que outros repitam o trabalho e especifica o tipo de pesquisa) e 4 Resultados e discussões (onde se testa a hipótese). Títulos e quantidade de seções variam.",
          "A conclusão (ou Considerações finais) é a última seção numerada: concentra os principais resultados de forma sucinta, retomando métodos, resultados, cumprimento do objetivo geral, importância da pesquisa e sugestões de trabalhos futuros.",
          "Os pós-textuais não são numerados. Só as referências são obrigatórias: listam todas as obras usadas, conforme a NBR 6023, e sua ausência pode levar à reprovação automática. Os demais são opcionais.",
        ],
        topicos: [
          "Glossário: termos especializados com seus significados, em ordem alfabética.",
          "Apêndice: material produzido pelo próprio autor (códigos-fonte, questionários aplicados, roteiros de entrevista, tabelas completas, protocolos de laboratório); identificado por letras maiúsculas, travessão e título.",
          "Anexo: material produzido por terceiros (leis, relatórios institucionais, fichas técnicas, folhas de dados de componentes), com a origem nas referências.",
          "Índice: lista de termos importantes com as páginas em que aparecem; pode haver mais de um.",
          "Títulos sem indicativo numérico (errata, agradecimentos, listas, resumos, sumário, referências, glossário, apêndices, anexos, índices) são centralizados e escritos em caixa-alta.",
        ],
      },
      {
        titulo: "Citações",
        paragrafos: [
          "Citação é a utilização de trechos, dados ou ideias de outros autores no nosso trabalho (dados do IBGE, informações de um fabricante, uma frase de Machado de Assis). As citações mostram que a pesquisa se baseia em fontes confiáveis, situam o trabalho no campo de estudo e fortalecem a argumentação. Referência é a disposição padronizada das informações que identificam a obra de origem. Chamada é a indicação, próxima à citação, que liga o conteúdo à sua referência. Usar bem os três evita o plágio.",
          "Citação direta é a transcrição literal, sem modificar palavras nem pontuação; é mais comum nas ciências jurídicas e humanas. A direta curta (até três linhas) fica entre aspas duplas, com a formatação do texto. A direta longa (mais de três linhas) tem recuo de 4 cm da margem esquerda, espaçamento simples e fonte menor (geralmente 10, mas a NBR 10520 não fixa tamanho) e dispensa aspas. A chamada pode vir antes, “Perkovic (2016, p. 3)”, ou depois, “(Perkovic, 2016, p. 3)”.",
          "Citação indireta usa ideias ou dados de outra obra com nossas próprias palavras, sem destaque visual. A chamada e a referência continuam obrigatórias; só o número da página é dispensado. É útil para adaptar a linguagem ao público e trazer dados estatísticos.",
          "Citação de citação é a citação, direta ou indireta, retirada de uma obra que não é a origem da ideia, quando o original não está acessível. Usa-se apud (“citado por”): Souza (1983, p. 297, apud Silva, 2025, p. 32). Nas referências entra apenas a obra consultada (Silva), e não a original.",
        ],
      },
      {
        titulo: "Sistemas de chamada e referências",
        paragrafos: [
          "Pela NBR 10520 (2023), deve-se escolher um único sistema de chamada, autor-data ou numérico, e usá-lo de forma consistente em todo o trabalho.",
          "No sistema autor-data, a lista de referências fica em ordem alfabética pelo sobrenome do primeiro autor. No sistema numérico, as citações recebem números consecutivos em algarismos arábicos, entre parênteses ou sobrescritos; a mesma fonte repetida recebe o mesmo número; na citação direta, acrescenta-se a página, como em (5, p. 30); e a lista de referências segue a ordem em que as obras aparecem no texto.",
          "Pela NBR 6023 (2018), a referência tem elementos essenciais (indispensáveis à identificação) e, quando necessário, complementares (que, se usados, devem aparecer em todas as referências do mesmo tipo). A ficha catalográfica da obra ajuda a montar a referência.",
        ],
        topicos: [
          "Autor-data, pessoa física: sobrenome e ano, mais a página nas citações diretas; “[...]” indica trecho omitido.",
          "Autor-data, pessoa jurídica: nome completo ou sigla em maiúsculas, como (IBGE, 2011, p. 3); órgão governamental da administração direta: nome da jurisdição, como (Brasil, 1995).",
          "Sem autoria: chamada pelo título, como (Inglês, 2012, p. 7), ou pela primeira palavra seguida de [...] quando o título é longo.",
          "Quatro ou mais autores: pode-se indicar só o primeiro seguido de et al.; com menos de quatro, todos aparecem.",
          "Livro: autor, título em destaque (negrito ou itálico), subtítulo, edição, local, editora e ano. Trabalho acadêmico: acrescenta ano de depósito, tipo, grau e curso, vinculação acadêmica e data da defesa.",
          "Documento online: acrescenta “Disponível em:” e “Acesso em:”; em mídia física (CD-ROM, DVD), a descrição do suporte.",
          "Artigo de periódico: o destaque vai no título do periódico, com volume, número, páginas e data; em meio eletrônico, acrescenta-se o DOI quando houver.",
          "Documento de acesso exclusivo em meio eletrônico (bases de dados, programas, redes sociais): autor, título, versão, local, data e descrição do meio.",
        ],
      },
      {
        titulo: "Ferramentas de pesquisa e plágio",
        paragrafos: [
          "Catálogos de obras acadêmicas: Minha Biblioteca (livros eletrônicos em português com acesso integral, de editoras como LTC, Érica, Saraiva e Atlas); Biblioteca Virtual Pearson (livros em português da Pearson e parceiras como Contexto e Blucher); BDTD, Biblioteca Digital Brasileira de Teses e Dissertações (trabalhos stricto sensu de mais de cem instituições, coordenada pelo Ibict, com busca por título, autor, ano, assunto ou resumo); e Portal de Periódicos da Capes (grande acervo virtual com milhares de periódicos de texto completo, inclusive Nature e Science, além de patentes, normas e teses).",
          "Plágio, segundo Krokoscz, é uma modalidade de fraude: a apropriação indevida, parcial ou integral, de obra alheia, apresentada como própria. A Lei n. 9.610/1998 regula os direitos autorais e prevê o recolhimento do material plagiado e/ou indenização ao autor. Usar conteúdo de terceiros não só é permitido como é mandatório; o que caracteriza o plágio é a omissão da fonte.",
          "Ferramentas de detecção: o CopySpider (gratuito para uso pessoal) compara o arquivo com documentos da internet e, a partir da versão 2.6.0, gera um índice de semelhança S, que é baixo abaixo de 10%, moderado de 10% a menos de 30% e alto a partir de 30% (nas versões antigas, o ideal era ficar abaixo de 3%). O Plagium funciona online, com limite de 1000 caracteres na versão gratuita. O SafeAssign, integrado ao Blackboard, compara também com um banco institucional de trabalhos. Em todos, a análise humana do relatório é indispensável.",
        ],
        topicos: [
          "Plágio direto: cópia literal sem citar a fonte.",
          "Plágio indireto: reprodução da ideia, com outras palavras, sem citar a fonte.",
          "Plágio mosaico: trechos de obras diferentes misturados com outras palavras.",
          "Plágio consentido: apresentar como próprio um trabalho cedido por terceiros ou comprado.",
          "Autoplágio: republicar trabalho próprio já publicado como se fosse original (algumas áreas aceitam, por diretriz própria).",
        ],
      },
      {
        titulo: "Pesquisa, inovação e prática de mercado",
        paragrafos: [
          "Pesquisa científica é a atividade sistemática voltada a aumentar o conhecimento em uma área; ela pode ou não levar a uma inovação. Para Vasconcellos, inovação é “uma ideia que sofreu alguma ação, com resultados positivos para todas as partes interessadas”. Há a inovação baseada na ciência (conhecimento vindo de pesquisa própria ou absorvido de fora), que é o foco do material, e a inovação baseada na prática (conhecimento criado no local de trabalho, nas experiências e interações do dia a dia).",
          "Segundo Cordaro, a demanda é a principal motivação da inovação. No exemplo do fabricante de baterias insatisfeito com a duração das baterias de smartphones, ele não começa do zero: usa o conhecimento disponível e faz pesquisa aplicada, por isso a pesquisa é mandatória para a inovação. Prática de mercado é a ampla incorporação das inovações por empresas e indústrias: se a bateria tiver bom custo-benefício, baixo impacto ambiental e boa performance, tende a virar prática de mercado. O processo é pesquisa → inovação → prática de mercado.",
        ],
        topicos: [
          "Vacinas de mRNA: primeira aprovação em 2020 (Moderna e Pfizer/BioNTech), mas o mRNA foi descoberto nos anos 1960 e estudado para vacinas desde os 1970. Em vez de partes do agente morto ou atenuado, usam um mRNA sintético que faz as células produzirem uma proteína inofensiva do agente, gerando resposta imune. Vantagens: fabricação simples, baixo custo e produção rápida. Nem sempre impedem a doença, mas reduzem sua gravidade.",
          "Crispr/Cas9: descoberta em 2012 por Emmanuelle Charpentier e Jennifer Doudna (Nobel de Química de 2020). O Crispr é um sistema de defesa natural de bactérias; a proteína Cas9 funciona como “tesoura molecular” que corta o DNA no ponto exato. Primeiro uso em humanos publicado em 2019; em 2023, o Reino Unido foi o primeiro país a aprovar uma terapia com a técnica (anemia falciforme e talassemia beta).",
          "Soja tropicalizada: a Embrapa (1972) criou a Embrapa Soja em 1975. Fora do sul do Brasil, a soja florescia precocemente e perdia produtividade; nos anos 1970 a Embrapa desenvolveu uma variedade que inibe o florescimento. A soja virou o principal produto de exportação do país e impulsionou maquinário, transporte e urbanização. Em 2025, Mariangela Hungria, da Embrapa Soja, recebeu o World Food Prize por insumos biológicos.",
        ],
      },
      {
        titulo: "Inovações computacionais: hardware",
        paragrafos: [
          "Boa parte dos recursos de computação surgiu em universidades e centros de pesquisa, e a ciência usa intensamente a computação para simulação e controle de experimentos. Hardware é a parte física e tocável do sistema (monitor, teclado, memória, processador, placas).",
          "Transistor: os primeiros computadores usavam relês (muito lentos) e válvulas (queimavam com frequência e consumiam muita energia) como interruptores. A pesquisa começou na Segunda Guerra, pela necessidade de receber micro-ondas, tarefa que as válvulas não davam conta, usando cristais de germânio (semicondutor). Em 1947, John Bardeen e Walter Brattain, da Bell Labs (fundada em 1925), construíram o transistor de ponto de contato: uma lâmina de ouro cortada sobre uma cunha de plástico, apoiada no cristal; a corrente na base fazia a corrente fluir do emissor para o coletor (ligado) e, sem ela, parava (desligado). É um interruptor em estado sólido, sem partes móveis, rápido e confiável. William Shockley criou o transistor de junção bipolar em 1948, e o de efeito de campo se difundiu nos anos 1970. Bardeen, Brattain e Shockley ganharam o Nobel de Física.",
          "Circuito integrado: nos anos 1950, conectar cada vez mais transistores individuais era difícil (uma solda defeituosa inviabilizava o computador) e os fios longos atrasavam os sinais. O circuito integrado reúne vários dispositivos já conectados em um bloco de semicondutor, sem soldas nem fios. O britânico George Dummer idealizou o conceito (publicou em 1952 e construiu um flip-flop em 1957), mas os britânicos não investiram. Jack Kilby, da Texas Instruments, obteve o primeiro circuito integrado patenteado (1960), e Robert Noyce, da Fairchild, chegou à mesma ideia de forma independente (1959); as empresas reconheceram a invenção mútua. Kilby recebeu o Nobel de Física em 2000. Hoje os chips são de silício e permitiram a miniaturização.",
        ],
      },
      {
        titulo: "Inovações computacionais: software",
        paragrafos: [
          "Software é a parte lógica e não palpável do sistema: o conjunto de programas, escritos em linguagens de programação, que recebem, manipulam e geram dados.",
          "Linguagem C: criada por Dennis Ritchie na Bell Labs, com compilador concluído em 1972, e padronizada pela ANSI em 1989. Evoluiu da BCPL (Martin Richards, Cambridge, 1966) e da B (Ken Thompson e Ritchie, 1969), acrescentando tipos de dados e estruturas de controle. Nasceu ligada ao Unix, reescrito em C em 1972. Só se popularizou após o livro The C Programming Language (Kernighan e Ritchie, 1978). É usada em kernels, firmware, drivers, sistemas embarcados, firewalls e compiladores, e influenciou C++, Java, C# e Python (o CPython é escrito em C).",
          "World Wide Web: em 1989, o físico Tim Berners-Lee, do Cern, propôs no documento “Information Management: a proposal” organizar as informações por hipertexto acessível em rede, depois de descartar árvores de diretórios e palavras-chave. Até 1990 criou HTML (formata documentos), URI, hoje URL (endereço único de cada página), e HTTP (comunicação entre navegador e servidor). A primeira página foi ao ar no fim de 1990 e, em 1991, pessoas de fora do Cern já podiam acessá-la; em 1993 os servidores passaram de 50 para várias centenas. Ela transformou a comunicação científica, com acesso instantâneo a artigos e repositórios.",
          "Redes neurais: modelo de aprendizado de máquina (ramo da inteligência artificial) que simula neurônios. Tem camadas de nós (entrada, ao menos uma intermediária e saída); cada nó tem peso e limiar e é ativado quando sua saída passa do limiar. Marcos: McCulloch e Pitts (1943), regra de Hebb (1949), Turing (1950), perceptron de Rosenblatt (1958) e a arquitetura Transformer, em “Attention is all you need” (Vaswani et al., 2017). Aplicações: busca do Google, recomendações do YouTube, ChatGPT e DeepSeek. Python é hoje uma das linguagens mais relevantes na área.",
        ],
      },
    ],
    pontosChave: [
      "Quatro tipos de conhecimento: popular (senso comum), filosófico (razão), teológico (fé em dogmas) e científico (método sistemático).",
      "Dedução: do geral para o específico, conclusão necessária. Indução: do específico para o geral, conclusão provável.",
      "Hipótese é suposição testável; lei descreve o que acontece; teoria explica por que e como acontece.",
      "Método experimental é indutivo (fatos → hipóteses → leis); método matemático é dedutivo (leis → teorias).",
      "Pesquisa quantitativa mede com números; qualitativa compreende significados. Básica amplia o conhecimento; aplicada resolve problemas.",
      "Mestrado não exige originalidade; doutorado exige contribuição inédita. Lato sensu é especialização; stricto sensu é mestrado e doutorado.",
      "Obrigatórios na monografia: capa, folha de rosto, folha de aprovação, resumo, resumo em língua estrangeira, sumário, introdução, desenvolvimento, conclusão e referências.",
      "Apêndice é feito pelo próprio autor; anexo é feito por terceiros.",
      "Citação direta curta (até 3 linhas) vai entre aspas; a longa tem recuo de 4 cm, fonte menor e sem aspas. Indireta dispensa a página, mas não a chamada.",
      "Apud indica citação de citação; nas referências entra só a obra consultada.",
      "Autor-data ordena as referências alfabeticamente; o sistema numérico, pela ordem de citação no texto.",
      "Plágio é omitir a fonte. Tipos: direto, indireto, mosaico, consentido e autoplágio.",
      "Pesquisa → inovação → prática de mercado; a demanda é a principal motivação da inovação.",
      "Transistor (Bell Labs, 1947), circuito integrado (Kilby e Noyce), linguagem C (Ritchie, 1972), Web (Berners-Lee, Cern, 1989) e redes neurais nasceram de pesquisa científica.",
    ],
  },

  // ------------------------------------------------------------------
  quiz: [
    {
      pergunta: "Um avô ensina o neto a fazer pão dizendo que é preciso esperar a massa “dobrar de tamanho”, sem explicar a fermentação. Que tipo de conhecimento está sendo transmitido?",
      alternativas: ["Conhecimento popular", "Conhecimento filosófico", "Conhecimento teológico", "Conhecimento científico"],
      correta: 0,
      explicacao: "É conhecimento popular (senso comum): adquirido espontaneamente, pela observação e pela prática, sem método e sem os fundamentos científicos do processo.",
    },
    {
      pergunta: "Qual característica do conhecimento científico indica que suas hipóteses não são incontestáveis nem imutáveis?",
      alternativas: ["Falibilidade", "Factualidade", "Sistematicidade", "Contingência"],
      correta: 0,
      explicacao: "Falibilidade: como as hipóteses podem ser refutadas por novas evidências, o conhecimento científico é considerado falível, ao contrário dos dogmas.",
    },
    {
      pergunta: "“Todo homem é mortal; Sócrates é um homem; portanto, Sócrates é mortal.” Esse é um exemplo de:",
      alternativas: ["Raciocínio dedutivo", "Raciocínio indutivo", "Formulação de hipótese", "Pesquisa qualitativa"],
      correta: 0,
      explicacao: "É dedução: parte de premissas gerais para uma conclusão específica, que é necessariamente verdadeira se as premissas forem verdadeiras e o raciocínio for válido.",
    },
    {
      pergunta: "Qual é a diferença entre uma lei e uma teoria científica?",
      alternativas: [
        "A lei descreve o que acontece; a teoria explica por que e como acontece",
        "A lei é uma hipótese ainda não testada; a teoria já foi testada",
        "A lei é exclusiva das ciências sociais; a teoria, da física",
        "A lei é uma opinião pessoal; a teoria é uma descrição matemática",
      ],
      correta: 0,
      explicacao: "A lei descreve um padrão observado (geralmente em forma matemática), sem explicar o motivo. A teoria é uma explicação abrangente que integra leis, hipóteses e evidências e faz previsões testáveis.",
    },
    {
      pergunta: "No método científico, qual etapa vem logo depois da observação dos fatos?",
      alternativas: ["Pesquisa bibliográfica", "Formulação da teoria", "Verificação experimental", "Publicação dos resultados"],
      correta: 0,
      explicacao: "Depois de observar, o cientista reúne o que já foi publicado sobre o assunto (pesquisa bibliográfica) e, com isso e com o raciocínio, formula a hipótese.",
    },
    {
      pergunta: "Uma pesquisa aplica um questionário com perguntas fechadas a 1000 estudantes e usa estatística para relacionar horas em redes sociais e notas. Quanto à abordagem, ela é:",
      alternativas: ["Quantitativa", "Qualitativa", "Documental", "Pesquisa-ação"],
      correta: 0,
      explicacao: "Ela trabalha primariamente com dados numéricos e métodos estatísticos para mensurar e generalizar, o que caracteriza a abordagem quantitativa.",
    },
    {
      pergunta: "Um estudo busca entender como o cérebro armazena memórias de longo prazo, sem pensar em uma aplicação imediata. Quanto à natureza, é uma pesquisa:",
      alternativas: ["Básica (pura)", "Aplicada", "Experimental", "De levantamento"],
      correta: 0,
      explicacao: "Pesquisa básica amplia o conhecimento científico sem se preocupar com aplicação prática imediata; a aplicada busca resolver um problema específico.",
    },
    {
      pergunta: "O que diferencia a tese de doutorado da dissertação de mestrado?",
      alternativas: [
        "A tese exige uma contribuição inédita (originalidade) para a ciência",
        "A tese dispensa a defesa diante de banca",
        "A dissertação exige descobertas revolucionárias",
        "A dissertação é um curso lato sensu",
      ],
      correta: 0,
      explicacao: "Na dissertação não é obrigatório apresentar originalidade; essa exigência é feita para a tese, cuja contribuição inédita não precisa ser revolucionária, mas deve representar um avanço.",
    },
    {
      pergunta: "O que é a revisão por pares (peer review)?",
      alternativas: [
        "A análise crítica do artigo por especialistas da mesma área antes da publicação",
        "A leitura do artigo pelos colegas de turma do autor",
        "A tradução do artigo para o inglês",
        "A apresentação do artigo em uma sessão de pôsteres",
      ],
      correta: 0,
      explicacao: "Na revisão por pares, outros especialistas da área avaliam qualidade, originalidade, validade e relevância e enviam sugestões, garantindo a credibilidade da pesquisa.",
    },
    {
      pergunta: "Qual elemento da parte externa de uma monografia é opcional e só existe em trabalhos encadernados em capa dura?",
      alternativas: ["Lombada", "Capa", "Folha de rosto", "Errata"],
      correta: 0,
      explicacao: "A lombada é opcional e aparece apenas em encadernação de capa dura; não existe em encadernação espiral ou em trabalhos exclusivamente digitais. A capa é obrigatória.",
    },
    {
      pergunta: "Quando o resumo em língua vernácula de uma monografia deve ser escrito?",
      alternativas: [
        "Depois que a parte textual estiver concluída",
        "Antes de começar a introdução",
        "Junto com a folha de rosto, no início do trabalho",
        "Somente se a banca pedir",
      ],
      correta: 0,
      explicacao: "Embora seja um elemento pré-textual, o resumo sintetiza introdução, desenvolvimento e conclusão, por isso só pode ser escrito depois que a parte textual estiver pronta.",
    },
    {
      pergunta: "Na introdução, qual elemento indica o motivo pelo qual é importante resolver o problema e dá credibilidade à pesquisa?",
      alternativas: ["Justificativa", "Contextualização", "Hipótese", "Objetivo específico"],
      correta: 0,
      explicacao: "A justificativa explica por que vale a pena resolver o problema. A contextualização diz sobre o que é o trabalho e a hipótese traz a resposta que o autor imagina.",
    },
    {
      pergunta: "Um estudante quer incluir no fim da monografia o código-fonte que ele mesmo escreveu. Esse material deve entrar como:",
      alternativas: ["Apêndice", "Anexo", "Glossário", "Índice"],
      correta: 0,
      explicacao: "Apêndice é material produzido pelo próprio autor; anexo é material produzido por terceiros, como leis ou folhas de dados.",
    },
    {
      pergunta: "Qual é o único elemento pós-textual obrigatório?",
      alternativas: ["Referências", "Glossário", "Apêndice", "Índice"],
      correta: 0,
      explicacao: "Apenas as referências são obrigatórias entre os pós-textuais; glossário, apêndices, anexos e índices são opcionais.",
    },
    {
      pergunta: "Como deve ser formatada uma citação direta com mais de três linhas?",
      alternativas: [
        "Recuo de 4 cm da margem esquerda, espaçamento simples, fonte menor e sem aspas",
        "Entre aspas duplas, com a mesma formatação do texto",
        "Em itálico, sem chamada",
        "Em parágrafo comum, com o número da página no fim do trabalho",
      ],
      correta: 0,
      explicacao: "A citação direta longa recebe destaque visual (recuo de 4 cm, espaçamento simples e fonte menor), que dispensa as aspas. Aspas são usadas na citação direta curta.",
    },
    {
      pergunta: "Na citação de citação, o que significa a expressão apud?",
      alternativas: ["Citado por", "E outros", "Página omitida", "Sem data"],
      correta: 0,
      explicacao: "Apud significa “citado por” e indica a fonte intermediária, como em Souza (1983, apud Silva, 2025). “E outros” é o significado de et al.",
    },
    {
      pergunta: "No sistema numérico de chamada, como a lista de referências é ordenada?",
      alternativas: [
        "Pela ordem em que as obras são citadas no texto",
        "Em ordem alfabética pelo sobrenome do primeiro autor",
        "Pelo ano de publicação, da mais antiga para a mais recente",
        "Por tipo de documento (livros, artigos, sites)",
      ],
      correta: 0,
      explicacao: "No sistema numérico, a referência número 5 é a quinta obra citada no texto. A ordem alfabética é usada no sistema autor-data.",
    },
    {
      pergunta: "Um aluno entrega como seu um trabalho que comprou de outra pessoa. Que tipo de plágio é esse?",
      alternativas: ["Plágio consentido", "Plágio mosaico", "Autoplágio", "Plágio indireto"],
      correta: 0,
      explicacao: "Plágio consentido é apresentar como próprio um trabalho cedido por terceiros (amigos, colegas) ou comprado.",
    },
    {
      pergunta: "Segundo Cordaro, qual é a principal motivação para uma inovação?",
      alternativas: ["A demanda", "O aumento populacional", "A publicação de artigos", "A redução de impostos"],
      correta: 0,
      explicacao: "A demanda traz uma necessidade que precisa de solução, e por isso é considerada a principal motivação da inovação, como no exemplo das baterias de smartphones.",
    },
    {
      pergunta: "Por que o transistor substituiu relês e válvulas nos computadores?",
      alternativas: [
        "Era um interruptor em estado sólido, rápido e confiável",
        "Era um dispositivo mecânico com partes móveis mais resistentes",
        "Consumia mais energia, mas era mais barato",
        "Dispensava o uso de material semicondutor",
      ],
      correta: 0,
      explicacao: "Os relês eram lentos e as válvulas queimavam e consumiam muita energia. O transistor, feito de semicondutor e sem partes móveis, era rápido e confiável.",
    },
  ],

  // ------------------------------------------------------------------
  flashcards: [
    { tema: "Conhecimento", frente: "O que é conhecimento?", verso: "A percepção ou a compreensão de algo, obtida por meio da experiência, da reflexão, da prática ou do estudo." },
    { tema: "Conhecimento", frente: "Ciência e conhecimento são sinônimos?", verso: "Não. “Ciência” vem do latim scientia (conhecimento), mas ciência é o empreendimento coletivo que organiza o conhecimento por um método próprio e transparente, reduzindo incertezas sobre a realidade." },
    { tema: "Conhecimento", frente: "Conhecimento tácito × explícito", verso: "Tácito: internalizado, vem da experiência, da prática e da intuição; difícil de formalizar (ex.: habilidade de um cirurgião). Explícito: facilmente codificado em livros, manuais e documentos." },
    { tema: "Tipos de conhecimento", frente: "Quais são os quatro tipos principais de conhecimento?", verso: "Popular, filosófico, teológico e científico." },
    { tema: "Tipos de conhecimento", frente: "Características do conhecimento popular", verso: "Superficialidade (“porque eu vi”, “porque me disseram”), sensitividade (experiências e emoções) e subjetividade (a pessoa organiza os saberes sem método). Também é chamado de empírico." },
    { tema: "Tipos de conhecimento", frente: "Conhecimento filosófico", verso: "Usa a razão, a reflexão e a argumentação lógica para questionar problemas humanos (verdade, moral, sentido da vida), muitas vezes sem resposta definitiva." },
    { tema: "Tipos de conhecimento", frente: "Conhecimento teológico", verso: "Saber religioso ligado ao sagrado e ao transcendental; depende da fé em dogmas, não é verificável cientificamente e não é universal (varia entre religiões)." },
    { tema: "Tipos de conhecimento", frente: "O que é um dogma?", verso: "Uma afirmação religiosa aceita como verdadeira sem dúvida ou questionamento; é considerada incontestável e imutável. Ao contrário da hipótese, não está sujeita a testes." },
    { tema: "Tipos de conhecimento", frente: "Cinco características do conhecimento científico", verso: "Factualidade, contingência, sistematicidade, verificabilidade e falibilidade." },
    { tema: "Tipos de conhecimento", frente: "Contingência (conhecimento científico)", verso: "A veracidade ou falsidade das hipóteses é conhecida pela experimentação, e não apenas pela razão, como no conhecimento filosófico." },
    { tema: "Raciocínio", frente: "Raciocínio dedutivo", verso: "Parte de premissas gerais para conclusões específicas. Com premissas verdadeiras e raciocínio válido, a conclusão é necessariamente verdadeira. Ex.: Sócrates é mortal." },
    { tema: "Raciocínio", frente: "Raciocínio indutivo", verso: "Parte de premissas específicas para conclusões gerais; a conclusão é provável. Quanto mais premissas a apoiam, mais forte é o argumento. Ex.: o remédio R curou cinco pacientes, logo cura a doença D." },
    { tema: "Raciocínio", frente: "Qual raciocínio formula hipóteses e leis, e qual testa hipóteses e valida teorias?", verso: "O indutivo formula hipóteses e leis; o dedutivo testa hipóteses, aplica leis e valida teorias. Eles são complementares." },
    { tema: "Hipótese, lei e teoria", frente: "Hipótese", verso: "Proposição formulada como possível solução para um problema ou possível explicação para um fenômeno; ponto de partida que ainda precisa ser testado." },
    { tema: "Hipótese, lei e teoria", frente: "Lei científica", verso: "Descrição precisa de um padrão observado na natureza: diz o que acontece, mas não por quê. Muitas vezes expressa por uma fórmula; a física é a ciência que mais formula leis." },
    { tema: "Hipótese, lei e teoria", frente: "Teoria científica", verso: "Explicação abrangente e bem fundamentada para um conjunto de fenômenos: explica por que e como ocorrem, integra leis e evidências e faz previsões testáveis." },
    { tema: "Método científico", frente: "Etapas do método científico", verso: "Observação de fatos → pesquisa bibliográfica → formulação de hipótese → verificação experimental → replicação e consenso (lei) → teoria → sistema (ainda almejado)." },
    { tema: "Método científico", frente: "Método experimental × método matemático", verso: "Experimental: dominado pela indução, vai dos fatos às hipóteses gerais e às leis. Matemático: dominado pela dedução, parte das leis para hipóteses mais abrangentes e teorias." },
    { tema: "Tipos de pesquisa", frente: "Pesquisa quantitativa × qualitativa", verso: "Quantitativa: dados numéricos e estatística para medir, testar hipóteses e generalizar. Qualitativa: textos, entrevistas e observações para compreender significados e percepções." },
    { tema: "Tipos de pesquisa", frente: "Pesquisa básica × aplicada", verso: "Básica (pura): amplia o conhecimento sem aplicação imediata. Aplicada: resolve problemas ou desenvolve tecnologias, geralmente a partir da básica." },
    { tema: "Tipos de pesquisa", frente: "Pesquisa documental", verso: "Usa documentos oficiais, pessoais ou registros históricos como fonte de dados; comum em pesquisas históricas, jurídicas e sociológicas." },
    { tema: "Tipos de pesquisa", frente: "Pesquisa-ação", verso: "Pesquisadores e pessoas atingidas pelo problema trabalham de forma cooperativa para resolvê-lo e gerar conhecimento (ex.: gestão de resíduos com a comunidade escolar)." },
    { tema: "Tipos de pesquisa", frente: "Estudo de caso", verso: "Estudo aprofundado de uma situação específica para detalhá-la; é versátil e pode combinar outros procedimentos técnicos." },
    { tema: "Trabalhos acadêmicos", frente: "O que é uma monografia?", verso: "Trabalho acadêmico textual longo que documenta o estudo de um tema específico, feito na graduação ou pós-graduação e formatado pelo guia de normalização (baseado na ABNT)." },
    { tema: "Trabalhos acadêmicos", frente: "Um TCC é a mesma coisa que uma monografia?", verso: "Não. O TCC pode incluir a monografia, a defesa diante da banca e, às vezes, protótipos. A monografia é a principal documentação exigida." },
    { tema: "Trabalhos acadêmicos", frente: "Lato sensu × stricto sensu", verso: "Lato sensu (“em sentido amplo”): especialização, foco no mercado, título de especialista. Stricto sensu (“em sentido restrito”): mestrado e doutorado, foco acadêmico e científico." },
    { tema: "Trabalhos acadêmicos", frente: "Bacharel, licenciado e tecnólogo", verso: "Bacharel: formação generalista (direito, engenharias). Licenciado: forma professores (matemática, física). Tecnólogo: formação prática e técnica (análise e desenvolvimento de sistemas)." },
    { tema: "Artigos científicos", frente: "Onde fica a revisão bibliográfica em um artigo científico?", verso: "Na introdução, que também traz o objetivo, geralmente no último parágrafo." },
    { tema: "Artigos científicos", frente: "Para que serve a seção Material e métodos?", verso: "Detalhar materiais e procedimentos de modo que outros pesquisadores consigam replicar o estudo." },
    { tema: "Comunicação científica", frente: "Congresso × simpósio", verso: "Congresso: reúne várias áreas de um tema geral, de três a cinco dias, com palestras, apresentações orais, pôsteres e mesas-redondas. Simpósio: tema mais delimitado, de um a cinco dias." },
    { tema: "Comunicação científica", frente: "Como reconhecer divulgação científica confiável?", verso: "Verificar quem publica, identificar a autoria e o currículo, verificar se há referências e evitar sensacionalismo, curas milagrosas e tom alarmista." },
    { tema: "Estrutura da monografia", frente: "Quais são as partes de uma monografia (NBR 14724)?", verso: "Parte externa (capa obrigatória e lombada opcional) e parte interna (elementos pré-textuais, textuais e pós-textuais)." },
    { tema: "Estrutura da monografia", frente: "Elementos pré-textuais obrigatórios", verso: "Folha de rosto, folha de aprovação, resumo em língua vernácula, resumo em língua estrangeira e sumário." },
    { tema: "Estrutura da monografia", frente: "O que a folha de rosto acrescenta em relação à capa?", verso: "A natureza do trabalho (tipo, objetivo, instituição, área de concentração) e o nome do orientador e do coorientador. No verso, a ficha catalográfica." },
    { tema: "Estrutura da monografia", frente: "Regras do resumo (NBR 6028)", verso: "Parágrafo único, sem tópicos, entre 150 e 500 palavras, sintetizando todo o texto; ao final, pelo menos três palavras-chave separadas por ponto e vírgula e finalizadas por ponto." },
    { tema: "Estrutura da monografia", frente: "Errata", verso: "Elemento opcional usado quando há erros identificados após a impressão; indica folha, linha e correção e vem logo após a folha de rosto." },
    { tema: "Estrutura da monografia", frente: "O que a introdução costuma conter?", verso: "Contextualização, problema, hipótese (quando couber), justificativa, objetivo geral e específicos, breve menção aos métodos e apresentação das próximas seções." },
    { tema: "Estrutura da monografia", frente: "Apêndice × anexo", verso: "Apêndice: material produzido pelo próprio autor (código-fonte, questionário aplicado). Anexo: material de terceiros (lei, ficha técnica, folha de dados)." },
    { tema: "Citações", frente: "Citação, referência e chamada", verso: "Citação: uso de trechos, dados ou ideias de outros autores. Referência: dados padronizados que identificam a obra. Chamada: indicação no texto que liga a citação à referência." },
    { tema: "Citações", frente: "Citação direta curta × longa", verso: "Curta (até 3 linhas): entre aspas duplas, formatação do texto. Longa (mais de 3 linhas): recuo de 4 cm, espaçamento simples, fonte menor, sem aspas." },
    { tema: "Citações", frente: "O que a citação indireta dispensa?", verso: "Apenas o número da página e o destaque visual. A chamada e a referência continuam obrigatórias." },
    { tema: "Citações", frente: "Citação de citação", verso: "Citação retirada de uma obra que não é a origem da ideia. Usa apud (“citado por”) e, nas referências, entra só a obra consultada." },
    { tema: "Chamadas e referências", frente: "Quando usar et al. na chamada autor-data?", verso: "Quando a obra tem quatro ou mais autores: indica-se apenas o primeiro, seguido de et al." },
    { tema: "Chamadas e referências", frente: "Elementos essenciais × complementares (NBR 6023)", verso: "Essenciais: indispensáveis para identificar a obra. Complementares: caracterizam melhor a obra e, se usados, devem aparecer em todas as referências do mesmo tipo." },
    { tema: "Plágio", frente: "O que é plágio?", verso: "Apropriação indevida, parcial ou integral, de obra alheia apresentada como própria (Krokoscz). O que o constitui é a omissão da fonte. A Lei n. 9.610/1998 protege os direitos autorais." },
    { tema: "Plágio", frente: "Plágio mosaico", verso: "Reprodução de trechos de obras diferentes misturados com outras palavras para dar sentido ao texto, sem citar as fontes." },
    { tema: "Plágio", frente: "Interpretação do índice S do CopySpider (versão 2.6.0 em diante)", verso: "Baixa: S < 10%. Moderada: 10% ≤ S < 30%. Alta: S ≥ 30%. A análise humana do relatório continua indispensável." },
    { tema: "Ferramentas de pesquisa", frente: "BDTD", verso: "Biblioteca Digital Brasileira de Teses e Dissertações: repositório de trabalhos stricto sensu de mais de cem instituições, coordenado pelo Ibict." },
    { tema: "Inovação", frente: "Definição de inovação (Vasconcellos)", verso: "“Uma ideia que sofreu alguma ação, com resultados positivos para todas as partes interessadas.” Pode ser baseada na ciência ou na prática." },
    { tema: "Inovação", frente: "O que é prática de mercado?", verso: "A ampla incorporação de uma inovação nas práticas de empresas, fábricas e indústrias. Processo: pesquisa → inovação → prática de mercado." },
    { tema: "Inovação", frente: "Como funcionam as vacinas de mRNA?", verso: "Um mRNA sintético faz as células produzirem uma proteína inofensiva do agente infeccioso, e o organismo desenvolve resposta imune a ela, sem ser exposto ao agente." },
    { tema: "Inovação", frente: "Crispr/Cas9", verso: "Técnica de edição genética (Charpentier e Doudna, 2012; Nobel de Química de 2020). A proteína Cas9 age como tesoura molecular que corta o DNA no ponto exato." },
    { tema: "Inovação", frente: "Soja tropicalizada", verso: "Variedade desenvolvida pela Embrapa nos anos 1970 que inibe o florescimento precoce fora do sul do Brasil, permitindo expandir a produção; hoje a soja é o principal produto de exportação do país." },
    { tema: "Hardware", frente: "Quem criou o primeiro transistor operacional?", verso: "John Bardeen e Walter Brattain, na Bell Labs, em 1947 (transistor de ponto de contato, com cristal de germânio)." },
    { tema: "Hardware", frente: "Que problemas o circuito integrado resolveu?", verso: "A dificuldade de soldar cada vez mais transistores (uma solda ruim inviabilizava o computador) e o atraso dos sinais em fios longos. Os dispositivos já vêm conectados em um bloco de semicondutor." },
    { tema: "Software", frente: "Linguagem C", verso: "Criada por Dennis Ritchie na Bell Labs (1972), sucessora da B; ligada ao Unix; popularizada pelo livro de Kernighan e Ritchie (1978). Usada em kernels, drivers, firmware e sistemas embarcados." },
    { tema: "Software", frente: "Três tecnologias que formam o “coração” da Web", verso: "HTML (formata documentos), URI/URL (endereço único de cada página) e HTTP (comunicação entre navegador e servidor). Criadas por Tim Berners-Lee no Cern." },
    { tema: "Software", frente: "Como um nó de uma rede neural é ativado?", verso: "Cada nó tem peso e limiar; quando sua saída fica acima do limiar, ele é ativado e envia os dados à próxima camada." },
  ],

  // ------------------------------------------------------------------
  prova: {
    titulo: "Prova de Pesquisa, Tecnologia e Inovação — Unidades I a IV",
    questoesPorTentativa: 20,
    questoes: [
      {
        tema: "Tipos de conhecimento",
        enunciado: "Por muito tempo se disse que tomar leite com manga faz mal, e muitas pessoas acreditam nisso “porque todo mundo diz”. À luz do material, essa crença é um exemplo de conhecimento:",
        alternativas: [
          "Científico, pois foi transmitido por várias gerações",
          "Popular, que é tradicionalmente aceito, mas pode ou não estar correto",
          "Filosófico, pois resulta de reflexão racional sobre a alimentação",
          "Teológico, pois depende de um dogma revelado",
          "Científico, pois se baseia em fatos observados no cotidiano",
        ],
        correta: 1,
        explicacao: "É conhecimento popular: superficial (“porque é o que todo mundo diz”), não testado por método científico e, por isso, de validade incerta. O material cita esse exemplo como um mito perpetuado pela tradição.",
      },
      {
        tema: "Tipos de conhecimento",
        enunciado: "Duas estudantes debatem se mentir é eticamente aceitável. Uma diz que mentir sempre quebra a confiança; a outra, que mentir pode salvar uma vida. Elas não chegam a um acordo, mas ampliam sua compreensão do tema. Esse processo caracteriza o conhecimento:",
        alternativas: [
          "Popular, pois envolve opiniões pessoais",
          "Teológico, pois trata de certo e errado",
          "Filosófico, que busca aprofundar a compreensão pela razão, sem exigir respostas definitivas",
          "Científico, pois as hipóteses foram confrontadas",
          "Empírico, pois foi obtido pela experiência cotidiana",
        ],
        correta: 2,
        explicacao: "O conhecimento filosófico usa a reflexão racional e a argumentação lógica para discutir questões humanas, como a ética, muitas vezes sem respostas definitivas. O objetivo é aprofundar a compreensão.",
      },
      {
        tema: "Tipos de conhecimento",
        enunciado: "Qual afirmação compara corretamente um dogma e uma hipótese?",
        alternativas: [
          "Ambos são aceitos sem questionamento até que surjam novas evidências",
          "O dogma é testado em laboratório; a hipótese é aceita pela fé",
          "O dogma é uma lei científica ainda não comprovada",
          "O dogma é incontestável e imutável; a hipótese está sempre sujeita a testes e à refutação",
          "A hipótese só existe no conhecimento filosófico",
        ],
        correta: 3,
        explicacao: "Dogma é uma afirmação religiosa aceita como verdadeira, incontestável e imutável. A hipótese, ao contrário, deve sempre poder ser testada e refutada, mudando conforme novas evidências.",
      },
      {
        tema: "Tipos de conhecimento",
        enunciado: "Um grupo afirma que determinada energia invisível cura doenças, mas não há como observá-la, medi-la ou testá-la. Segundo as características do conhecimento científico, essa afirmação não pertence à ciência por falta de:",
        alternativas: ["Subjetividade", "Superficialidade", "Sensitividade", "Verificabilidade", "Tradição"],
        correta: 3,
        explicacao: "Pela verificabilidade, afirmações que não podem ser comprovadas não pertencem ao âmbito da ciência. Subjetividade, superficialidade e sensitividade são características do conhecimento popular.",
      },
      {
        tema: "Tipos de conhecimento",
        enunciado: "Em uma empresa, um técnico experiente percebe pelo som que uma máquina vai falhar, mas não consegue explicar nem registrar como sabe disso. No contexto da gestão do conhecimento, isso é um exemplo de conhecimento:",
        alternativas: ["Explícito", "Formal", "Tácito", "Objetivo", "Documental"],
        correta: 2,
        explicacao: "O conhecimento tácito é internalizado, vem da experiência, da prática e da intuição e é difícil de formalizar, documentar e transmitir. O explícito pode ser codificado em manuais e documentos.",
      },
      {
        tema: "Raciocínio",
        enunciado: "Observa-se que o corvo 1 é negro, o corvo 2 é negro, o corvo 3 é negro e assim por diante; conclui-se que todo corvo é negro. Sobre esse raciocínio, é correto afirmar:",
        alternativas: [
          "É dedutivo, e a conclusão é necessariamente verdadeira",
          "É indutivo, e a conclusão é provável, ficando mais forte quanto mais casos a apoiam",
          "É dedutivo, pois parte de uma regra geral",
          "É indutivo, e a conclusão é necessariamente verdadeira",
          "Não é um raciocínio lógico, pois não tem premissas",
        ],
        correta: 1,
        explicacao: "Parte de casos específicos para uma conclusão geral, o que caracteriza a indução. A conclusão é provável, e o argumento é mais forte quanto mais premissas o sustentam.",
      },
      {
        tema: "Raciocínio",
        enunciado: "Sobre a relação entre os raciocínios dedutivo e indutivo e a construção da ciência, assinale a correta:",
        alternativas: [
          "A indução é essencial para formular hipóteses e leis, e a dedução para testar hipóteses e validar teorias",
          "A dedução é usada apenas na filosofia, e a indução apenas na ciência",
          "Os dois raciocínios são excludentes; o cientista deve escolher um",
          "A dedução produz conclusões apenas prováveis",
          "A indução parte de leis gerais para casos específicos",
        ],
        correta: 0,
        explicacao: "Os raciocínios são complementares: a indução gera hipóteses e leis a partir de casos particulares, e a dedução testa hipóteses, aplica leis e valida teorias.",
      },
      {
        tema: "Hipótese, lei e teoria",
        enunciado: "Biólogos mostram que a velocidade de um inseto segue v = 0,4·T − 2 até 40 °C, resultado replicado no mundo todo, e depois explicam o fenômeno pela taxa metabólica e pelo estresse térmico. A função e a explicação correspondem, respectivamente, a:",
        alternativas: ["Hipótese e lei", "Teoria e hipótese", "Lei e teoria", "Teoria e lei", "Hipótese e teoria"],
        correta: 2,
        explicacao: "A função descreve o que acontece (lei); a explicação de por que acontece, integrando lei e evidências, é a teoria. A hipótese foi o ponto de partida: “se a temperatura aumentar, a velocidade aumentará”.",
      },
      {
        tema: "Hipótese, lei e teoria",
        enunciado: "Alguém diz: “Minha teoria é que ele esqueceu o celular porque estava com pressa”. Do ponto de vista científico, essa frase:",
        alternativas: [
          "Usa o termo corretamente, pois toda teoria começa como suposição",
          "Descreve uma lei, pois relata um padrão",
          "Expressa um dogma",
          "Usa “teoria” no sentido popular; cientificamente, trata-se de uma hipótese",
          "Expressa uma teoria, pois explica por que algo aconteceu",
        ],
        correta: 3,
        explicacao: "Na ciência, teoria é uma explicação abrangente, testada e bem fundamentada. Uma suposição inicial ainda não testada é uma hipótese, que é o sentido do uso popular da palavra.",
      },
      {
        tema: "Método científico",
        enunciado: "Na estrutura lógica do método científico apresentada por Severino, o método experimental e o método matemático são dominados, respectivamente, por qual raciocínio?",
        alternativas: [
          "Indutivo e dedutivo",
          "Dedutivo e indutivo",
          "Indutivo nos dois casos",
          "Dedutivo nos dois casos",
          "Filosófico e teológico",
        ],
        correta: 0,
        explicacao: "O método experimental vai dos fatos às hipóteses gerais e às leis (indução). O método matemático parte das leis para hipóteses mais abrangentes e teorias (dedução).",
      },
      {
        tema: "Método científico",
        enunciado: "Uma hipótese foi confirmada experimentalmente por um pesquisador. Segundo o material, o que ainda é necessário, de forma geral, para que ela se torne uma lei?",
        alternativas: [
          "A aprovação de um órgão governamental",
          "A publicação em um livro didático",
          "A replicação dos resultados e o consenso da comunidade científica",
          "Que ela seja expressa por uma fórmula, sem necessidade de repetição",
          "Que ela seja transformada em um sistema universal",
        ],
        correta: 2,
        explicacao: "Uma hipótese confirmada pode encaminhar-se para virar lei, o que depende da replicação dos resultados e do consenso da comunidade científica.",
      },
      {
        tema: "Tipos de pesquisa",
        enunciado: "Uma pesquisa faz perguntas abertas a 50 estudantes, como “Como você descreve sua experiência com redes sociais nos estudos?”, e analisa temas recorrentes nas respostas. Quanto à abordagem e à coleta, ela é:",
        alternativas: [
          "Quantitativa e experimental",
          "Qualitativa e de levantamento",
          "Quantitativa e documental",
          "Qualitativa e experimental",
          "Básica e documental",
        ],
        correta: 1,
        explicacao: "Os dados não são numéricos e buscam compreender percepções (qualitativa), e foram coletados por questionário aplicado a uma amostra de pessoas (levantamento).",
      },
      {
        tema: "Tipos de pesquisa",
        enunciado: "Sobre pesquisa básica e pesquisa aplicada, é correto afirmar:",
        alternativas: [
          "A pesquisa aplicada dispensa o conhecimento gerado por pesquisas básicas",
          "A pesquisa básica sempre gera um produto comercial",
          "Desenvolver um medicamento para Alzheimer é exemplo de pesquisa básica",
          "A pesquisa básica gera bases teóricas que possibilitam pesquisas aplicadas, e ambas são essenciais",
          "Apenas a pesquisa aplicada contribui para o avanço da ciência",
        ],
        correta: 3,
        explicacao: "A pesquisa básica amplia o conhecimento sem aplicação imediata e fornece a base teórica que a aplicada usa para resolver problemas. As duas são essenciais.",
      },
      {
        tema: "Tipos de pesquisa",
        enunciado: "Um historiador analisa atas de câmaras municipais e cartas do século XIX para entender a urbanização de uma cidade. Quanto aos procedimentos técnicos, essa é uma pesquisa:",
        alternativas: ["Experimental", "Pesquisa-ação", "De levantamento", "Documental", "Estudo de caso clínico"],
        correta: 3,
        explicacao: "A pesquisa documental usa documentos oficiais, pessoais ou registros históricos como fonte de dados e é comum em pesquisas históricas, jurídicas e sociológicas.",
      },
      {
        tema: "Tipos de pesquisa",
        enunciado: "Pesquisadores se reúnem com professores, alunos e funcionários de uma escola para, juntos, investigar e implantar um programa de gestão de resíduos. Esse procedimento técnico é:",
        alternativas: ["Pesquisa bibliográfica", "Pesquisa experimental", "Pesquisa-ação", "Pesquisa documental", "Pesquisa básica"],
        correta: 2,
        explicacao: "Na pesquisa-ação, pesquisadores e participantes atingidos pelo problema atuam de forma cooperativa para resolvê-lo e gerar conhecimento a partir disso.",
      },
      {
        tema: "Trabalhos acadêmicos",
        enunciado: "Um aluno afirma que “TCC e monografia são exatamente a mesma coisa”. Segundo o material:",
        alternativas: [
          "Está correto, pois o TCC é apenas o documento escrito",
          "Está incorreto: o TCC pode incluir a monografia, a defesa diante da banca e, às vezes, protótipos",
          "Está incorreto, pois o TCC nunca inclui monografia",
          "Está correto apenas em cursos tecnológicos",
          "Está incorreto, pois monografia só existe no doutorado",
        ],
        correta: 1,
        explicacao: "O TCC é composto de etapas: produção e entrega da monografia, apresentação para a banca e, em alguns casos, elementos práticos. A monografia é a principal documentação exigida.",
      },
      {
        tema: "Trabalhos acadêmicos",
        enunciado: "Uma profissional quer um curso de pós-graduação com foco na aplicação prática do conhecimento no mercado de trabalho. Ela deve procurar um curso:",
        alternativas: [
          "Stricto sensu, que confere o título de especialista",
          "Lato sensu, que confere o título de especialista",
          "Stricto sensu de doutorado, que exige originalidade",
          "Lato sensu, que confere o título de mestre",
          "De licenciatura, que forma professores",
        ],
        correta: 1,
        explicacao: "A pós-graduação lato sensu (“em sentido amplo”) é a especialização, voltada ao mercado, e confere o título de especialista. Stricto sensu corresponde a mestrado e doutorado.",
      },
      {
        tema: "Trabalhos acadêmicos",
        enunciado: "Um mestrando faz uma pesquisa aprofundada e rigorosa, mas sem nenhuma descoberta inédita. Em relação à exigência de originalidade, seu trabalho:",
        alternativas: [
          "Será reprovado, pois toda dissertação exige contribuição inédita",
          "Pode ser aprovado, pois a originalidade é exigida apenas na tese de doutorado",
          "Precisa ser convertido em artigo científico",
          "Deve ser apresentado como trabalho de graduação",
          "Só será aceito se for revolucionário",
        ],
        correta: 1,
        explicacao: "Na dissertação de mestrado não é obrigatório apresentar originalidade. A contribuição inédita, que não precisa ser revolucionária, é exigida na tese de doutorado.",
      },
      {
        tema: "Artigos científicos",
        enunciado: "Um pesquisador lê um artigo e quer repetir exatamente o mesmo experimento em seu laboratório. Em qual seção do artigo ele deve buscar essas informações?",
        alternativas: ["Resumo", "Introdução", "Material e métodos", "Agradecimentos", "Palavras-chave"],
        correta: 2,
        explicacao: "Material e métodos detalha os materiais e os procedimentos adotados para que outros pesquisadores consigam replicar o estudo.",
      },
      {
        tema: "Comunicação científica",
        enunciado: "Em um evento científico, os autores ficam ao lado de um resumo visual de suas pesquisas enquanto os participantes circulam e conversam com eles, sem apresentações individuais. Trata-se de:",
        alternativas: ["Palestra", "Mesa-redonda", "Apresentação oral", "Sessão de pôsteres", "Defesa de tese"],
        correta: 3,
        explicacao: "Na sessão de pôsteres cada pesquisador expõe um resumo visual da pesquisa e fica próximo para explicá-lo, num formato mais dinâmico, sem apresentações individuais.",
      },
      {
        tema: "Comunicação científica",
        enunciado: "Qual destas publicações apresenta mais sinais de NÃO ser uma divulgação científica confiável?",
        alternativas: [
          "Um texto de universidade que cita os artigos em que se baseou",
          "Um vídeo de pesquisador com currículo verificável que simplifica o tema sem distorcê-lo",
          "Uma matéria de um centro de pesquisa como a Fiocruz",
          "Um texto anônimo, sem referências, que promete uma cura milagrosa",
          "Um artigo de divulgação publicado pela revista Nature",
        ],
        correta: 3,
        explicacao: "Os critérios do material são: verificar quem publica, identificar a autoria, conferir as referências e evitar sensacionalismo. Um texto anônimo, sem fontes e com cura milagrosa falha em todos.",
      },
      {
        tema: "Estrutura da monografia",
        enunciado: "Um aluno vai entregar sua monografia apenas em formato digital (PDF). Quanto à parte externa, ele deve:",
        alternativas: [
          "Incluir capa e lombada, ambas obrigatórias",
          "Incluir apenas a lombada",
          "Incluir a capa, que é obrigatória; a lombada não deve existir",
          "Dispensar a capa, pois o trabalho é digital",
          "Substituir a capa pela folha de aprovação",
        ],
        correta: 2,
        explicacao: "A capa é obrigatória em qualquer monografia. A lombada é opcional, usada apenas em encadernação de capa dura, e não deve existir em trabalhos espirais ou exclusivamente digitais.",
      },
      {
        tema: "Estrutura da monografia",
        enunciado: "Qual grupo reúne apenas elementos pré-textuais obrigatórios, segundo a NBR 14724?",
        alternativas: [
          "Folha de rosto, dedicatória, epígrafe e sumário",
          "Errata, resumo, lista de tabelas e sumário",
          "Folha de rosto, folha de aprovação, resumo, resumo em língua estrangeira e sumário",
          "Agradecimentos, resumo, lista de símbolos e sumário",
          "Capa, folha de rosto, introdução e referências",
        ],
        correta: 2,
        explicacao: "São pré-textuais obrigatórios: folha de rosto, folha de aprovação, resumo, resumo em língua estrangeira e sumário. Errata, dedicatória, agradecimentos, epígrafe e listas são opcionais; capa é parte externa.",
      },
      {
        tema: "Estrutura da monografia",
        enunciado: "Qual informação aparece na folha de aprovação, mas não na folha de rosto?",
        alternativas: [
          "O título do trabalho",
          "O nome do orientador",
          "A natureza do trabalho",
          "A data de aprovação e as assinaturas da banca examinadora",
          "A ficha catalográfica",
        ],
        correta: 3,
        explicacao: "A folha de aprovação acrescenta a data de aprovação e o nome, a titulação e a assinatura dos membros da banca, preenchidos após a aprovação. Natureza do trabalho, orientador e ficha catalográfica são da folha de rosto.",
      },
      {
        tema: "Estrutura da monografia",
        enunciado: "Um resumo foi escrito em três parágrafos com tópicos, tem 80 palavras e termina com duas palavras-chave separadas por vírgula. Quantas regras da NBR 6028 apresentadas no material ele descumpre?",
        alternativas: [
          "Nenhuma, pois o resumo é livre",
          "Apenas a do número de palavras-chave",
          "Todas: deveria ter parágrafo único sem tópicos, entre 150 e 500 palavras e ao menos três palavras-chave separadas por ponto e vírgula",
          "Apenas a da extensão, que deveria ter até 50 palavras",
          "Apenas o uso de tópicos, que é recomendado",
        ],
        correta: 2,
        explicacao: "O resumo deve ter parágrafo único, sem tópicos, extensão conveniente de 150 a 500 palavras e, ao final, pelo menos três palavras-chave separadas por ponto e vírgula e finalizadas por ponto.",
      },
      {
        tema: "Estrutura da monografia",
        enunciado: "Sobre as listas pré-textuais de uma monografia, é correto afirmar:",
        alternativas: [
          "A lista de tabelas é obrigatória e vem após a conclusão",
          "A lista de abreviaturas e siglas segue a ordem alfabética, e a de ilustrações segue a ordem em que aparecem no texto",
          "A lista de símbolos é obrigatória em trabalhos de exatas",
          "Uma monografia só pode ter uma única lista de ilustrações",
          "As listas substituem o sumário",
        ],
        correta: 1,
        explicacao: "Todas as listas são opcionais. A de abreviaturas e siglas é alfabética; as de ilustrações e tabelas seguem a ordem do texto, com número, legenda e página. Pode haver mais de uma lista de ilustrações.",
      },
      {
        tema: "Elementos textuais",
        enunciado: "Na introdução de uma dissertação lê-se: “como realizar a deposição do ITO em baixas temperaturas, em diferentes substratos?”. Esse trecho corresponde a qual elemento da introdução?",
        alternativas: ["Justificativa", "Hipótese", "Problema", "Objetivo geral", "Contextualização"],
        correta: 2,
        explicacao: "O problema apresenta a situação que se pretende resolver, geralmente em forma de pergunta, e delimita o tema. A hipótese seria a resposta que o autor imagina para essa pergunta.",
      },
      {
        tema: "Elementos textuais",
        enunciado: "Em uma dissertação, a seção em que os dados obtidos são apresentados, interpretados e usados para testar a hipótese é:",
        alternativas: ["Introdução", "Revisão da literatura", "Materiais e métodos", "Resultados e discussões", "Referências"],
        correta: 3,
        explicacao: "Em Resultados e discussões os dados são apresentados, comentados e interpretados; é ali que se testa a hipótese e se tenta resolver o problema da pesquisa.",
      },
      {
        tema: "Elementos textuais",
        enunciado: "Segundo o material, uma boa conclusão de monografia deve:",
        alternativas: [
          "Apresentar pela primeira vez o referencial teórico",
          "Ser uma seção não numerada, depois das referências",
          "Retomar brevemente métodos e resultados, mostrar o cumprimento do objetivo geral, destacar a importância da pesquisa e sugerir trabalhos futuros",
          "Trazer novas hipóteses sem relação com os resultados",
          "Repetir integralmente a introdução",
        ],
        correta: 2,
        explicacao: "A conclusão é a última seção numerada da parte textual e concentra, de forma sucinta, os principais resultados, o cumprimento do objetivo, a importância da pesquisa e sugestões de trabalhos futuros.",
      },
      {
        tema: "Elementos pós-textuais",
        enunciado: "Um estudante de computação quer incluir no fim do trabalho (1) o roteiro de entrevista que ele criou e (2) a folha de dados de um microcontrolador, publicada pelo fabricante. Esses materiais entram, respectivamente, como:",
        alternativas: ["Anexo e apêndice", "Apêndice e anexo", "Glossário e índice", "Apêndice e apêndice", "Anexo e anexo"],
        correta: 1,
        explicacao: "Apêndice é material produzido pelo próprio autor (o roteiro); anexo é material produzido por terceiros (a folha de dados), cuja origem deve constar nas referências.",
      },
      {
        tema: "Citações",
        enunciado: "Um aluno transcreve literalmente cinco linhas de um livro, coloca o trecho entre aspas, sem recuo e com a mesma fonte do texto. O correto seria:",
        alternativas: [
          "Manter assim, pois toda citação direta vai entre aspas",
          "Aplicar recuo de 4 cm, espaçamento simples e fonte menor, sem aspas",
          "Transformar o trecho em nota de rodapé",
          "Retirar a chamada, pois o trecho é longo",
          "Colocar o trecho em itálico e eliminar a referência",
        ],
        correta: 1,
        explicacao: "Com mais de três linhas, é uma citação direta longa: recebe recuo de 4 cm, espaçamento simples e fonte menor, e esse destaque dispensa as aspas.",
      },
      {
        tema: "Citações",
        enunciado: "Um aluno reescreve com suas próprias palavras uma ideia de Perkovic (2016) e coloca apenas “Segundo Perkovic (2016)”, sem número de página. Essa citação:",
        alternativas: [
          "Está errada, pois toda citação exige o número da página",
          "Está correta: é uma citação indireta, que dispensa a página, mas mantém chamada e referência",
          "É plágio, pois não usou aspas",
          "É uma citação direta curta",
          "Dispensa a inclusão da obra nas referências",
        ],
        correta: 1,
        explicacao: "Na citação indireta não há transcrição literal nem destaque visual, e o número da página é dispensado. A chamada e a referência continuam obrigatórias.",
      },
      {
        tema: "Citações",
        enunciado: "Você leu no livro de Silva (2025) uma frase de Souza (1983), cujo livro está esgotado e você não conseguiu consultar. Como deve fazer a chamada e o que entra nas referências?",
        alternativas: [
          "Souza (1983); apenas o livro de Souza entra nas referências",
          "Silva (2025); nenhum autor precisa ser referenciado",
          "Souza (1983, apud Silva, 2025); entra nas referências apenas o livro de Silva",
          "Silva et al. (2025); entram os dois livros nas referências",
          "Souza e Silva (1983); entra apenas o livro mais antigo",
        ],
        correta: 2,
        explicacao: "Na citação de citação, a chamada traz os dois autores ligados por apud (“citado por”). Nas referências entra apenas a obra efetivamente consultada, a de Silva.",
      },
      {
        tema: "Sistemas de chamada",
        enunciado: "Um livro foi escrito por cinco autores: Lima, Souza, Oliveira, Santos e Pereira. No sistema autor-data, uma chamada aceita é:",
        alternativas: [
          "(Lima, 2024) sem indicação de outros autores",
          "Lima et al. (2024)",
          "(Pereira et al., 2024)",
          "(Lima apud Souza, 2024)",
          "(5, p. 2024)",
        ],
        correta: 1,
        explicacao: "Com quatro ou mais autores, é possível indicar apenas o primeiro seguido de et al. Apud é usado na citação de citação, e números são do sistema numérico.",
      },
      {
        tema: "Sistemas de chamada",
        enunciado: "Sobre os sistemas de chamada da NBR 10520 (2023), assinale a alternativa correta:",
        alternativas: [
          "O autor pode alternar entre autor-data e numérico em cada seção",
          "No sistema numérico, a mesma obra citada duas vezes recebe dois números diferentes",
          "No sistema numérico, as referências ficam em ordem alfabética",
          "Deve-se escolher um único sistema e usá-lo de forma consistente em todo o trabalho",
          "No sistema autor-data, as referências seguem a ordem de citação no texto",
        ],
        correta: 3,
        explicacao: "A norma exige escolher autor-data ou numérico e segui-lo consistentemente. No numérico, a fonte repetida mantém o mesmo número e a lista segue a ordem de citação; no autor-data, a lista é alfabética.",
      },
      {
        tema: "Sistemas de chamada",
        enunciado: "Para citar diretamente um texto do Instituto Brasileiro de Geografia e Estatística no sistema autor-data, a forma recomendada é:",
        alternativas: [
          "(Instituto Brasileiro, 2011)",
          "(IBGE, 2011, p. 3)",
          "(Instituto et al., 2011)",
          "(Brasil apud IBGE, 2011)",
          "(Geografia, 2011, p. 3)",
        ],
        correta: 1,
        explicacao: "Para pessoa jurídica, usa-se o nome completo ou a sigla da instituição, e a ABNT recomenda siglas em letras maiúsculas. Na citação direta, a página é incluída.",
      },
      {
        tema: "Referências",
        enunciado: "Ao referenciar um e-book acessado pela internet, além dos elementos essenciais de um livro, é necessário incluir:",
        alternativas: [
          "Apenas o número de páginas",
          "O endereço eletrônico precedido de “Disponível em:” e a data precedida de “Acesso em:”",
          "A ficha catalográfica completa",
          "O nome do orientador",
          "O DOI, que é obrigatório para todo documento online",
        ],
        correta: 1,
        explicacao: "Para documentos online, a NBR 6023 exige registrar o endereço eletrônico (“Disponível em:”) e a data de acesso (“Acesso em:”). O DOI é incluído em artigos eletrônicos quando houver.",
      },
      {
        tema: "Referências",
        enunciado: "Na referência de um artigo publicado em periódico, qual elemento recebe destaque (negrito ou itálico)?",
        alternativas: [
          "O título do artigo",
          "O nome do primeiro autor",
          "O título do periódico",
          "O número das páginas",
          "O local de publicação",
        ],
        correta: 2,
        explicacao: "Em artigos de periódicos, o destaque vai no título do periódico. Em livros, o destaque vai no título do livro.",
      },
      {
        tema: "Plágio",
        enunciado: "Um aluno juntou frases de três artigos diferentes, ligou-as com palavras próprias para dar sentido ao texto e não citou nenhuma fonte. Esse caso é de plágio:",
        alternativas: ["Direto", "Consentido", "Mosaico", "Autoplágio", "Indireto"],
        correta: 2,
        explicacao: "Plágio mosaico é a reprodução de trechos de obras diferentes misturados com outras palavras para que o texto tenha sentido, sem identificação das fontes.",
      },
      {
        tema: "Plágio",
        enunciado: "Um pesquisador publica de novo, como se fosse inédito, um artigo seu que já tinha sido publicado em outra revista. Sobre esse caso:",
        alternativas: [
          "Não há plágio, pois o autor é o mesmo",
          "É plágio consentido, pois o autor consentiu",
          "É autoplágio, que compromete a originalidade, embora algumas áreas aceitem o procedimento por diretriz própria",
          "É plágio mosaico",
          "É uma citação de citação",
        ],
        correta: 2,
        explicacao: "Autoplágio é republicar trabalho próprio já publicado como se fosse original. Não há terceiros envolvidos, mas a originalidade é comprometida; algumas áreas o aceitam por diretriz própria.",
      },
      {
        tema: "Plágio",
        enunciado: "O CopySpider (versão 2.6.0 ou posterior) retornou S = 15% na comparação de um trabalho com um documento da internet. Isso significa:",
        alternativas: [
          "Semelhança baixa, e o trabalho está automaticamente aprovado",
          "Semelhança moderada: 15% do texto de entrada aparece no outro documento, e o relatório deve passar por análise humana",
          "Semelhança alta, o que comprova plágio",
          "Que 85% do texto foi copiado",
          "Que o resultado está acima do ideal de 30%",
        ],
        correta: 1,
        explicacao: "Pela escala do fabricante, 10% ≤ S < 30% é semelhança moderada, e S = 15% indica que 15 de cada 100 trechos foram encontrados no outro documento. A análise humana do relatório é sempre indispensável.",
      },
      {
        tema: "Ferramentas de pesquisa",
        enunciado: "Um aluno quer encontrar dissertações e teses produzidas em programas de pós-graduação stricto sensu de diversas universidades brasileiras. O catálogo mais indicado é:",
        alternativas: [
          "A Biblioteca Virtual Pearson",
          "A Minha Biblioteca",
          "A BDTD, coordenada pelo Ibict",
          "O Plagium",
          "O SafeAssign",
        ],
        correta: 2,
        explicacao: "A Biblioteca Digital Brasileira de Teses e Dissertações reúne trabalhos stricto sensu de mais de cem instituições. Pearson e Minha Biblioteca são de livros; Plagium e SafeAssign detectam plágio.",
      },
      {
        tema: "Inovação",
        enunciado: "Um fabricante, diante da insatisfação dos usuários com a duração das baterias de smartphones, faz pesquisa aplicada, cria uma bateria melhor e, com o tempo, ela passa a ser usada por toda a indústria. Esse caso ilustra:",
        alternativas: [
          "Uma inovação baseada na prática, sem relação com pesquisa",
          "O processo pesquisa → inovação → prática de mercado, motivado por uma demanda",
          "Uma pesquisa básica sem aplicação imediata",
          "Uma prática de mercado que dispensa inovação",
          "Um caso em que a pesquisa é opcional para a inovação",
        ],
        correta: 1,
        explicacao: "A demanda motivou a inovação, que usou conhecimento científico e pesquisa aplicada (a pesquisa é mandatória). Sendo viável e bem aceita, a inovação virou prática de mercado.",
      },
      {
        tema: "Inovação",
        enunciado: "Segundo Vasconcellos, qual é a diferença entre inovação baseada na ciência e inovação baseada na prática?",
        alternativas: [
          "Não há diferença; são o mesmo tipo de atividade",
          "A baseada na ciência usa conhecimento de pesquisa própria ou externa; a baseada na prática cria conhecimento no local de trabalho, a partir de experiências e interações diárias",
          "A baseada na prática só ocorre em universidades",
          "A baseada na ciência dispensa pesquisa",
          "Ambas são consequência natural do aumento populacional",
        ],
        correta: 1,
        explicacao: "Na inovação baseada na ciência, o conhecimento vem de pesquisas próprias ou absorvidas de fora; na baseada na prática, surge nas experiências, observações e interações do trabalho. O material foca na primeira.",
      },
      {
        tema: "Inovações gerais",
        enunciado: "Qual afirmação sobre as vacinas de mRNA está de acordo com o material?",
        alternativas: [
          "Expõem o vacinado a uma parte do vírus morto ou atenuado",
          "Foram criadas do zero em 2020, sem pesquisa anterior",
          "Usam um mRNA sintético que leva as células a produzirem uma proteína inofensiva do agente, gerando resposta imune",
          "Sempre impedem que a pessoa fique doente",
          "Têm produção lenta e cara, o que dificulta a adoção em larga escala",
        ],
        correta: 2,
        explicacao: "As vacinas de mRNA fazem as células produzirem uma proteína do agente, sem exposição a ele. A primeira foi aprovada em 2020, mas o mRNA é estudado desde os anos 1960; a produção é simples, barata e rápida, e muitas vezes a vacina reduz a gravidade sem impedir a doença.",
      },
      {
        tema: "Inovações gerais",
        enunciado: "Sobre a técnica Crispr/Cas9, assinale a correta:",
        alternativas: [
          "Foi a primeira forma de edição genética testada em humanos",
          "A Cas9 é uma proteína que funciona como tesoura molecular, cortando o DNA no ponto exato a ser editado",
          "Foi descoberta em 2020 e ainda não tem uso comercial",
          "É um sistema de defesa natural do corpo humano",
          "O Brasil foi o primeiro país a aprovar uma terapia com a técnica",
        ],
        correta: 1,
        explicacao: "O Crispr é um sistema de defesa de bactérias adaptado pela ciência, e a Cas9 corta o DNA com precisão. A técnica foi descoberta em 2012, não foi a primeira edição genética em humanos e o Reino Unido aprovou a primeira terapia em 2023.",
      },
      {
        tema: "Inovações gerais",
        enunciado: "Qual problema a soja tropicalizada, desenvolvida pela Embrapa, resolveu?",
        alternativas: [
          "O ataque de pragas no sul do país",
          "O florescimento precoce da soja fora do sul do Brasil, que reduzia a produtividade",
          "A falta de chuvas no Nordeste",
          "A necessidade de vacinar o gado",
          "A baixa qualidade do solo amazônico",
        ],
        correta: 1,
        explicacao: "Fora do sul, a soja florescia precocemente em dias mais longos e perdia produtividade. A Embrapa desenvolveu, nos anos 1970, uma variedade que inibe o florescimento, permitindo expandir a produção.",
      },
      {
        tema: "Hardware",
        enunciado: "No transistor de ponto de contato construído na Bell Labs em 1947, o que fazia a corrente fluir do emissor para o coletor (estado “ligado”)?",
        alternativas: [
          "Um movimento mecânico, como em um interruptor de lâmpada",
          "A aplicação de corrente no terminal de base",
          "O aquecimento da válvula",
          "A troca do germânio por silício",
          "A remoção da lâmina de ouro",
        ],
        correta: 1,
        explicacao: "Com corrente aplicada na base, o circuito se fechava e a corrente fluía do emissor para o coletor; sem ela, parava. É um interruptor comandado eletricamente, sem partes móveis.",
      },
      {
        tema: "Hardware",
        enunciado: "Sobre a invenção do circuito integrado, é correto afirmar:",
        alternativas: [
          "Foi idealizado e financiado pelo governo britânico, que logo o comercializou",
          "Jack Kilby e Robert Noyce chegaram à ideia de forma independente, e as empresas reconheceram a invenção mútua",
          "Surgiu antes do transistor",
          "Aumentou a quantidade de soldas e fios entre os componentes",
          "Hoje é fabricado principalmente em germânio",
        ],
        correta: 1,
        explicacao: "Dummer idealizou o conceito, mas os britânicos não investiram. Kilby (Texas Instruments) e Noyce (Fairchild) inventaram o circuito de forma independente, eliminando soldas e fios. Hoje o padrão é o silício.",
      },
      {
        tema: "Software",
        enunciado: "Sobre a linguagem C, assinale a alternativa correta:",
        alternativas: [
          "Foi criada por Tim Berners-Lee no Cern",
          "Fez sucesso comercial imediato em 1972",
          "Evoluiu da linguagem B, acrescentando tipos de dados e estruturas de controle, e ainda é base de tecnologias como o CPython",
          "É usada hoje apenas em aplicações web de alto nível",
          "Antecedeu a BCPL e a B",
        ],
        correta: 2,
        explicacao: "A C, de Dennis Ritchie (Bell Labs, 1972), sucedeu a B e ganhou tipos de dados e estruturas de controle. Só se popularizou após o livro de 1978 e segue usada em kernels, drivers e no CPython.",
      },
      {
        tema: "Software",
        enunciado: "Ao propor a World Wide Web, como Tim Berners-Lee concluiu que deveriam ser organizadas as informações do Cern?",
        alternativas: [
          "Em árvores de diretórios, como o mundo real",
          "Por palavras-chave escolhidas por cada cientista",
          "Por hipertexto acessível pela rede mediante ferramentas universais",
          "Em CD-ROMs distribuídos aos pesquisadores",
          "Em um banco de dados central acessado por telefone",
        ],
        correta: 2,
        explicacao: "Ele descartou as árvores de diretórios (o mundo real não se organiza assim) e as palavras-chave (cada pessoa escolhe palavras diferentes) e propôs o hipertexto em rede, com HTML, URI e HTTP.",
      },
      {
        tema: "Software",
        enunciado: "Sobre redes neurais, é correto afirmar:",
        alternativas: [
          "São uma tecnologia surgida apenas após 2017",
          "Uma rede tradicional tem camada de entrada, ao menos uma intermediária e camada de saída, e cada nó é ativado quando sua saída ultrapassa o limiar",
          "Não têm relação com o aprendizado de máquina",
          "Funcionam sem pesos nem limiares",
          "São usadas apenas em hardware, não em software",
        ],
        correta: 1,
        explicacao: "Redes neurais são modelos de aprendizado de máquina com camadas de nós dotados de peso e limiar. Seus anos formativos foram de 1943 a 1958; em 2017 surgiu a arquitetura Transformer.",
      },
    ],
  },
});
