// Conteúdo de estudo da matéria Direitos Humanos.
// Gerado a partir dos arquivos desta pasta (livros-texto e slides das Unidades I e II).
registrarMateria({
  nome: "Direitos Humanos",
  descricao: "Teorias, características e dimensões dos direitos humanos, ONU, tratados, sistema interamericano, Constituição de 1988 e direitos sociais no Brasil.",
  arquivos: [
    "Livro-Texto - Unidade I.pdf",
    "Livro-Texto - Unidade II.pdf",
    "Slides de Aula - Unidade I.pdf",
    "Slides de Aula - Unidade II.pdf",
  ],

  // ------------------------------------------------------------------
  resumo: {
    titulo: "Direitos Humanos — Unidades I e II",
    secoes: [
      {
        titulo: "Sistema de proteção e teorias dos direitos humanos",
        paragrafos: [
          "A proteção dos direitos humanos não acontece de forma isolada: ela funciona como um sistema integrado, nacional e internacional, em que os organismos atuam em cadeia para denunciar violações, constranger o agressor e exigir que os governos punam os responsáveis. A ONU é o órgão responsável pelo sistema global de proteção.",
          "Três teorias explicam a criação dos direitos humanos. Segundo o Ministro Alexandre de Moraes, elas não se excluem: se completam e devem coexistir. A consciência social (moralista) baseada em valores universais (jusnaturalista) dá ao legislador o substrato para positivar direitos em lei (positivista).",
        ],
        topicos: [
          "Teoria jusnaturalista: todo ser humano tem direitos naturais pelo simples fato de ter nascido humano. Existem mesmo sem lei; são universais e imutáveis (ex.: vida e liberdade).",
          "Teoria positivista: são direitos humanos aqueles escolhidos pelo povo e seus governantes e positivados em lei, por serem fundamentais para a sociedade.",
          "Teoria moralista: são direitos humanos os que se coadunam com a moral de cada sociedade. Principal defensor: Charles Perelman (Varsóvia, 1912–1984).",
          "Não é preciso escolher uma teoria: as três são complementares.",
        ],
      },
      {
        titulo: "Definição de direitos humanos e dignidade da pessoa humana",
        paragrafos: [
          "Não há uma definição única, mas todas giram em torno da dignidade da pessoa humana. Para Alexandre de Moraes, direitos humanos fundamentais são “o conjunto institucionalizado de direitos e garantias do ser humano que tem por finalidade básica o respeito a sua dignidade, por meio de sua proteção contra o arbítrio do poder estatal e o estabelecimento de condições mínimas de vida e desenvolvimento da personalidade humana”. Nestor Sampaio Penteado Filho fala em “prerrogativas e garantias inerentes ao homem”, que o tutelam contra os excessos do Estado. Também são citados Pérez Luño e José Afonso da Silva.",
          "Dignidade é o valor próprio que identifica o ser humano como tal. Como ensina Ingo Sarlet, é mais fácil perceber quando a dignidade é agredida do que defini-la. Para Célia Zisman, o ordenamento jurídico não cria os direitos da pessoa, apenas os declara. Para o Ministro Luís Roberto Barroso, cada ser humano possui um valor intrínseco. A dignidade não exige contrapartida: vale para todos, inclusive para quem comete crimes.",
          "No Brasil, a dignidade da pessoa humana é fundamento da República (art. 1º, III, da CF/88), ao lado da soberania, da cidadania, dos valores sociais do trabalho e da livre iniciativa e do pluralismo político. Na Alemanha, a Lei Fundamental de 1949 declara a dignidade “intangível”.",
          "A expressão “pessoa humana” é um conceito jurídico: pessoa é o sujeito de direitos. Ela surgiu porque, ao longo da história, grupos (escravizados, judeus no Holocausto) tiveram negada a condição de pessoa. Por isso, a DUDH garante no art. VI que todo ser humano deve ser reconhecido como pessoa perante a lei.",
        ],
        topicos: [
          "Direitos humanos x direitos fundamentais: a diferença é meramente formal. Direitos humanos estão em tratados internacionais ou ainda não foram positivados; direitos fundamentais estão positivados em lei, especialmente na constituição.",
          "Vida digna = segurança, acesso à saúde, à educação e a emprego com salário que garanta o necessário para viver bem.",
          "O preconceito contra direitos humanos no Brasil (“direitos de bandidos”) nasce da insegurança, do desejo de vingança, de programas que exploram a violência e do desconhecimento de que a dignidade não requer contrapartida.",
        ],
      },
      {
        titulo: "Características dos direitos humanos",
        paragrafos: [
          "As características ajudam a identificar o rol de direitos humanos de uma sociedade. Diferente de direitos patrimoniais (como herança, que pode ser renunciada), os direitos humanos não podem ser restringidos nem renunciados pelo titular.",
        ],
        topicos: [
          "Universalidade: todos os seres humanos da Terra têm direito à proteção.",
          "Indivisibilidade: o rol forma um todo; o Estado não pode escolher alguns direitos e deixar outros de lado.",
          "Interdependência: os direitos são inter-relacionados; não há escala de relevância entre eles.",
          "Imprescritibilidade: ninguém perde o direito pelo decurso do tempo.",
          "Inalienabilidade: não podem ser transferidos, negociados ou cedidos, nem de graça nem por dinheiro.",
          "Irrenunciabilidade: ninguém pode renunciar a eles (à vida, à liberdade etc.).",
          "Efetividade: o Estado (Legislativo, Executivo e Judiciário) deve agir para torná-los reais.",
          "Inviolabilidade: ninguém, Estado ou pessoa física ou jurídica, pode desrespeitá-los.",
          "Complementaridade: devem ser interpretados em conjunto, nunca isoladamente.",
          "Vedação de retrocesso: uma vez reconhecido, um direito não pode ser retirado nem minimizado.",
        ],
      },
      {
        titulo: "Gerações ou dimensões dos direitos humanos",
        paragrafos: [
          "Os direitos humanos foram construídos aos poucos, conforme cada época histórica criou novas necessidades. A doutrina atual prefere “dimensões” a “gerações”, porque uma nova dimensão não encerra a anterior: todas se somam e se complementam (Penteado Filho).",
          "1ª dimensão — direitos civis e políticos (liberdades públicas), que protegem o cidadão contra o arbítrio do Estado. Marco simbólico: a Magna Carta de 1215, do rei João Sem-Terra, na Inglaterra, que limitou o poder do rei às leis. Também são marcos o Bill of Rights (1689), a Declaração de Direitos da Virgínia e a Declaração de Independência dos EUA (1776) e a Revolução Francesa (Queda da Bastilha, 1789). Valor: liberdade.",
          "2ª dimensão — direitos econômicos, sociais e culturais, surgidos com a Revolução Industrial (séc. XVIII): salário justo, limitação da jornada, férias, previdência, saúde, educação, lazer e cultura. Têm caráter coletivo. Marcos: Constituição Mexicana de 1917 (primeira a tratar direitos trabalhistas como fundamentais), Constituição de Weimar (1919) e criação da OIT (1919). Valor: igualdade.",
          "3ª dimensão — direitos de solidariedade ou fraternidade, tecnicamente difusos ou metaindividuais (pertencem a toda a humanidade). Surgem após a Segunda Guerra, diante de problemas coletivos: meio ambiente equilibrado, proteção do consumidor, progresso com paz e autodeterminação dos povos.",
          "4ª dimensão — direitos dos povos frente à globalização e ao avanço tecnológico: democracia, informação e pluralismo (Paulo Bonavides), com voz política para minorias sem representação. Inclui a proteção contra abusos da genética (Declaração Universal sobre o Genoma Humano e os Direitos Humanos, Unesco, 1997).",
          "5ª dimensão — direito à paz permanente, reforçado pelos atentados terroristas, como o de 11 de setembro. Para Bonavides, a paz é direito de todos os povos e dever dos governantes; no Brasil, a defesa da paz é princípio das relações internacionais (art. 4º, VI, CF). Alguns autores incluem aqui a proteção contra crimes na internet. Já se fala em uma 6ª dimensão: proteção de dados, genoma e biotecnologia.",
        ],
        topicos: [
          "1ª: liberdade — direitos civis e políticos (votar e ser votado, locomoção, expressão, processo justo).",
          "2ª: igualdade — direitos econômicos, sociais e culturais.",
          "3ª: fraternidade — direitos difusos (meio ambiente, consumidor, paz entre os povos).",
          "4ª: direitos dos povos — democracia, informação, pluralismo e bioética.",
          "5ª: paz permanente.",
          "Unesco (1997): o genoma humano é patrimônio da humanidade, não pode ser objeto de transações financeiras e a clonagem humana não deve ser permitida.",
        ],
      },
      {
        titulo: "Trajetória histórica: do direito humanitário a Nuremberg",
        paragrafos: [
          "A história dos direitos humanos começa, curiosamente, com regras para a guerra. A Conferência Internacional de Paz de Haia (1899) buscou soluções pacíficas para conflitos e regras a serem respeitadas nas guerras, originando o Direito Humanitário ou Direito Internacional da Guerra (proteção de feridos, náufragos, prisioneiros e civis).",
          "A Liga das Nações (1919), criada pelo Tratado de Versalhes, foi a precursora da ONU. Buscava cooperação, paz e segurança e relativizou a soberania dos Estados, prevendo sanções econômicas e militares a quem violasse suas obrigações. No mesmo ano surgiu a OIT, também prevista no Tratado de Versalhes (parte XIII), com a missão de promover trabalho decente e justiça social.",
          "O Tribunal de Nuremberg (1945–1946), criado pelo Acordo de Londres (1945), julgou principalmente oficiais nazistas por três categorias de crime: crimes contra a paz, crimes de guerra e crimes contra a humanidade. Foi criticado como um “tribunal dos vencedores contra os vencidos”, mas firmou a ideia de que até na guerra há limites éticos.",
        ],
        topicos: [
          "Crimes contra a paz: planejar, preparar ou incitar guerra de agressão.",
          "Crimes de guerra: violar leis e costumes da guerra (assassinato, maus-tratos a prisioneiros, deportação para trabalho escravo, destruição injustificada).",
          "Crimes contra a humanidade: assassinato, extermínio, escravização, deportação ou perseguição racial, política ou religiosa contra civis.",
          "O Tratado de Versalhes culpou apenas a Alemanha pela Primeira Guerra, fragilizando sua economia e criando condições para a ascensão de Hitler.",
        ],
      },
      {
        titulo: "A ONU: criação, estrutura e agências",
        paragrafos: [
          "A ideia da ONU surge na mensagem de Franklin Roosevelt ao Congresso dos EUA (6/1/1941) e na Carta do Atlântico (14/8/1941), assinada por Roosevelt e Winston Churchill. As Nações Unidas passaram a existir oficialmente em 24 de outubro de 1945, com sede em Nova York. O Brasil aprovou a Carta das Nações Unidas pelo Decreto-Lei n. 7.935/1945.",
          "A ONU tem 193 Estados-membros e seis órgãos principais: Assembleia Geral, Conselho de Segurança, Conselho Econômico e Social (ECOSOC), Conselho de Tutela, Corte (Tribunal) Internacional de Justiça e Secretariado.",
        ],
        topicos: [
          "Assembleia Geral: principal órgão deliberativo; cada país tem um voto; suas resoluções são recomendações, não obrigatórias; elege o Secretário-Geral.",
          "Conselho de Segurança: responsável pela paz; 15 membros — 5 permanentes com direito a veto (EUA, Rússia, Reino Unido, França e China) e 10 eleitos por dois anos. É o único órgão com poder decisório obrigatório.",
          "ECOSOC: coordena o trabalho econômico e social e promove os direitos humanos.",
          "Conselho de Tutela: suspenso em 1994, depois que Palau, último território tutelado, tornou-se independente.",
          "Corte Internacional de Justiça: sede em Haia; 15 juízes; somente países (nunca indivíduos) podem recorrer a ela.",
          "Agências: FAO (alimentação, sede em Roma), OMS/Opas (saúde), Unesco (educação, ciência e cultura, 1945), Unicef (infância, 1946; no Brasil desde 1950), ACNUR (refugiados, 1950), ONU Meio Ambiente (1972, Nairóbi), ONU-Habitat (1978, Nairóbi) e ONU Mulheres (2010).",
        ],
      },
      {
        titulo: "Declaração Universal dos Direitos Humanos (1948)",
        paragrafos: [
          "Adotada em 10 de dezembro de 1948 por 48 Estados, com oito abstenções e nenhum voto contrário, é o tratado de direitos humanos mais importante. Tem 30 artigos, e a única condição para ser titular dos direitos é ser pessoa. O Brasil é signatário e deve cumprir e fazer cumprir esses direitos.",
          "A Declaração conjuga dois valores: liberdade (direitos civis e políticos) e igualdade (direitos econômicos, sociais e culturais). Seu preâmbulo afirma que o reconhecimento da dignidade inerente a todos é o fundamento da liberdade, da justiça e da paz no mundo.",
        ],
        topicos: [
          "Art. I: todos nascem livres e iguais em dignidade e direitos e devem agir com espírito de fraternidade.",
          "Art. III: direito à vida, à liberdade e à segurança pessoal. Art. IV: proibição da escravidão. Art. V: proibição da tortura.",
          "Art. VI: direito de ser reconhecido como pessoa perante a lei.",
          "Art. IX: ninguém será arbitrariamente preso, detido ou exilado. Art. XI: presunção de inocência e irretroatividade da lei penal.",
          "Art. XIV: direito de asilo, que não vale para perseguição motivada por crimes comuns ou atos contrários à ONU.",
          "Arts. XXIII a XXVI: trabalho, repouso e lazer, padrão de vida adequado e instrução gratuita nos graus elementares.",
          "Art. XXIX: nenhum direito é absoluto; há deveres com a comunidade.",
        ],
      },
      {
        titulo: "Tratados internacionais de direitos humanos",
        paragrafos: [
          "Os Pactos Internacionais de 1966 complementam a DUDH. A ideia inicial era um único pacto, mas a Guerra Fria impediu: a União Soviética se opunha ao direito de propriedade privada. Por isso foram criados dois pactos. O Brasil só os adotou em 1992, após o fim da ditadura militar.",
        ],
        topicos: [
          "Pacto Internacional dos Direitos Civis e Políticos: liberdades públicas; cria o Comitê de Direitos Humanos; o art. 20 proíbe propaganda de guerra e apologia ao ódio; prevê um núcleo inderrogável (vida, proibição da tortura e da escravidão, proibição de prisão por dívida contratual, garantias penais, liberdade de pensamento, consciência e religião).",
          "Pacto Internacional dos Direitos Econômicos, Sociais e Culturais: trabalho, sindicatos, greve, seguridade, alimentação, moradia, educação; fiscalizado por relatórios ao ECOSOC.",
          "Convenção Relativa ao Estatuto dos Refugiados (1951, Convenção de Genebra): refugiado é quem está fora de seu país por fundado temor de perseguição por raça, religião, nacionalidade, grupo social ou opinião política. Migrante, ao contrário, desloca-se por escolha, em busca de melhores condições.",
          "Convenção sobre a Eliminação de Todas as Formas de Discriminação Racial (1965). O Dia Internacional pela Eliminação da Discriminação Racial (21 de março) lembra o Massacre de Sharpeville (África do Sul, 1960).",
          "Convenção sobre a Eliminação da Discriminação contra a Mulher (1979): prevê ações afirmativas; promulgada no Brasil em 2002.",
          "Convenção contra a Tortura (1984): define tortura e proíbe extraditar alguém para Estado onde corra risco de tortura; promulgada no Brasil em 1991.",
          "Convenção sobre os Direitos da Criança (1989): criança é todo menor de 18 anos, sujeito de direitos com absoluta prioridade; promulgada no Brasil em 1990.",
        ],
      },
      {
        titulo: "Sistema Interamericano de Direitos Humanos",
        paragrafos: [
          "Além do sistema global (ONU), existem sistemas regionais. Para as Américas, o sistema foi criado em 30 de abril de 1948, na IX Conferência Internacional Americana, em Bogotá, que resultou na Carta da OEA (em vigor desde dezembro de 1951). A OEA reúne os 35 Estados independentes das Américas e se apoia em quatro pilares: democracia, direitos humanos, segurança e desenvolvimento. Sua Assembleia Geral é o órgão mais importante e se reúne uma vez por ano.",
          "A Comissão Interamericana de Direitos Humanos (CIDH) foi criada em 1959 (Santiago, Chile) e instalada em 1960. Tem sete membros com mandato de quatro anos, com uma reeleição. O principal instrumento do sistema é a Convenção Americana de Direitos Humanos (Pacto de San José da Costa Rica), assinada em 1969 e em vigor desde 1978. O Brasil aderiu tardiamente, em 25/9/1992. O Protocolo de San Salvador (1988) acrescentou os direitos econômicos, sociais e culturais.",
          "Ao aderir à Convenção, o Estado aceita automaticamente que a Comissão examine petições individuais. A Comissão pede informações ao governo, investiga, busca uma solução amistosa e, se não houver acordo, elabora um relatório com recomendações e prazo de três meses. Apenas a Comissão e os Estados podem levar um caso à Corte Interamericana; o indivíduo não pode.",
          "A Corte Interamericana tem sete juízes e competência consultiva e contenciosa. Suas decisões são vinculantes e obrigatórias, e a compensação fixada à vítima vale como título executivo. O Brasil reconheceu a competência da Corte em dezembro de 1998.",
        ],
        topicos: [
          "Requisitos da petição individual: esgotamento dos recursos internos (salvo demora injustificada ou inexistência de processo) e inexistência de outra pendência internacional sobre o mesmo fato.",
          "Caso Maria da Penha: vítima de dupla tentativa de homicídio pelo marido em 1983 (ficou paraplégica). Em 2001, a CIDH responsabilizou o Brasil por omissão, negligência e tolerância, o que levou à Lei Maria da Penha (Lei n. 11.340/2006).",
        ],
      },
      {
        titulo: "A Constituição Federal de 1988",
        paragrafos: [
          "A CF/88 entrou em vigor em 5 de outubro de 1988, em cerimônia presidida por Ulysses Guimarães, presidente da Assembleia Nacional Constituinte. Foi a primeira após a ditadura militar (1964–1985), período em que vigorou o AI-5 (13/12/1968), que suspendeu direitos políticos, restringiu liberdades e acabou com as garantias de vitaliciedade, inamovibilidade e estabilidade dos magistrados, garantias que protegem o cargo para que o juiz decida com independência.",
          "Por isso, a CF/88 reconduziu o país à democracia e inaugurou o período do “direito de ter direitos”. Ela está no topo da hierarquia das leis (Constituição > leis federais > demais leis) e declara que os direitos nela previstos não excluem outros decorrentes de seus princípios ou de tratados internacionais de que o Brasil seja parte.",
        ],
        topicos: [
          "Fundamentos (art. 1º): soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político.",
          "Objetivos (art. 3º): sociedade livre, justa e solidária; desenvolvimento nacional; erradicar a pobreza e reduzir desigualdades; promover o bem de todos sem preconceitos.",
          "Cláusulas pétreas (art. 60, § 4º): forma federativa do Estado; voto direto, secreto, universal e periódico; separação dos Poderes; direitos e garantias individuais.",
          "Cláusula pétrea é de difícil modificação, mas não é imutável: só uma nova Assembleia Nacional Constituinte pode alterá-la.",
        ],
      },
      {
        titulo: "Direitos fundamentais individuais e coletivos (art. 5º)",
        paragrafos: [
          "Os direitos fundamentais estão principalmente no art. 5º, cujo rol é meramente exemplificativo, e não taxativo: outros direitos decorrentes dos princípios constitucionais e de tratados também são protegidos. Alexandre de Moraes classifica os direitos e garantias fundamentais em cinco espécies: individuais e coletivos, sociais, de nacionalidade, políticos e relativos aos partidos políticos.",
          "O caput do art. 5º garante que todos são iguais perante a lei e assegura a brasileiros e estrangeiros residentes a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.",
        ],
        topicos: [
          "I: homens e mulheres são iguais em direitos e obrigações. II: ninguém é obrigado a fazer ou deixar de fazer algo senão em virtude de lei.",
          "III: ninguém será submetido a tortura. IV: livre manifestação do pensamento, vedado o anonimato. V: direito de resposta e indenização.",
          "VI a VIII: liberdade de consciência e de crença; ninguém é privado de direitos por crença ou convicção.",
          "X: intimidade, vida privada, honra e imagem são invioláveis.",
          "XI: a casa é asilo inviolável; só se entra sem consentimento em flagrante delito, desastre, para prestar socorro ou, durante o dia, por determinação judicial.",
          "XII: sigilo da correspondência e das comunicações; a interceptação telefônica exige ordem judicial para investigação criminal. Equipamentos de trabalho não têm o mesmo sigilo.",
          "XV: livre locomoção em tempo de paz. XVI: reunião pacífica, sem armas, independente de autorização, com prévio aviso à autoridade.",
          "XVII e XX: liberdade de associação para fins lícitos (vedada a paramilitar); ninguém é obrigado a se associar.",
          "XXII e XXIII: direito de propriedade, que deve cumprir sua função social (imóvel rural improdutivo pode ser desapropriado para reforma agrária, art. 184).",
          "XXXII: o Estado promoverá a defesa do consumidor (Código de Defesa do Consumidor, Lei n. 8.078/1990).",
        ],
      },
      {
        titulo: "Direitos dos acusados e condenados",
        paragrafos: [
          "A sociedade civilizada pune, mas não se vinga: responder violência com violência nos igualaria ao criminoso. Por isso, a pena é a privação da liberdade, sem tortura, castigos corporais ou trabalhos forçados. A dignidade vale para todos, inclusive acusados e condenados, que muitas vezes podem ser inocentes.",
        ],
        topicos: [
          "XLV (pessoalidade): a pena não passa da pessoa do condenado; a obrigação de reparar o dano pode alcançar os sucessores até o limite do patrimônio transferido.",
          "XLVI (individualização da pena); XLVIII: estabelecimentos distintos conforme delito, idade e sexo; XLIX: respeito à integridade física e moral do preso.",
          "LIII: julgamento só pela autoridade competente. LIV: devido processo legal. LV: contraditório e ampla defesa.",
          "LVI: provas obtidas por meios ilícitos são inadmissíveis. LVII: ninguém é considerado culpado até o trânsito em julgado.",
          "LXXIV: assistência jurídica integral e gratuita (Defensoria Pública, art. 134). LXXV: o Estado indeniza o erro judiciário.",
          "Reclusão (crimes mais graves; pode começar no regime fechado), detenção (mais leves; não começa no fechado) e prisão simples (contravenções; só aberto ou semiaberto).",
        ],
      },
      {
        titulo: "Emenda Constitucional n. 45/2004 e Planos Nacionais de Direitos Humanos",
        paragrafos: [
          "A EC 45, de 30/12/2004, mudou o sistema de proteção no Brasil em três pontos. 1) Tratados de direitos humanos aprovados pelo Congresso em dois turnos, por três quintos dos votos, equivalem a emendas constitucionais. Os tratados anteriores têm status supralegal (acima das leis, abaixo da Constituição). O primeiro com status constitucional foi a Convenção sobre os Direitos das Pessoas com Deficiência. 2) O Brasil se submete ao Tribunal Penal Internacional (Haia, criado pelo Estatuto de Roma de 1998). 3) Permitiu a federalização de graves violações de direitos humanos.",
          "Na federalização, o Procurador-Geral da República pode suscitar, perante o STJ, incidente de deslocamento de competência para a Justiça Federal. O primeiro pedido foi o do assassinato da irmã Dorothy Stang (Pará, 2005), negado pelo STJ porque o Estado do Pará estava empenhado na apuração. A federalização é exceção e depende de proporcionalidade.",
          "Os Programas/Planos Nacionais de Direitos Humanos foram inspirados na Conferência de Viena da ONU (1993).",
        ],
        topicos: [
          "PNDH-1 (1996, Decreto 1.904): foco nos direitos civis e políticos (1ª dimensão).",
          "PNDH-2 (2002, Decreto 4.229): foco nos direitos econômicos, sociais, culturais e ambientais (2ª dimensão).",
          "PNDH-3 (2009, Decreto 7.037), baseado na 11ª Conferência Nacional de Direitos Humanos (2008). Seis eixos: Interação Democrática entre Estado e Sociedade Civil; Desenvolvimento e Direitos Humanos; Universalizar Direitos em um Contexto de Desigualdades; Segurança Pública, Acesso à Justiça e Combate à Violência; Educação e Cultura em Direitos Humanos; Direito à Memória e à Verdade.",
          "O PNDH-3 é acompanhado por um Comitê de 21 ministérios e por um grupo paritário (governo e sociedade civil) no CDDPH.",
        ],
      },
      {
        titulo: "Direitos sociais: saúde, educação e moradia",
        paragrafos: [
          "Os direitos sociais estão nos arts. 6º a 11 da CF. São “liberdades positivas” (Penteado Filho), ou seja, prestações positivas do Estado para melhorar a vida dos mais fracos e igualar situações desiguais (José Afonso da Silva). O art. 6º enumera: educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência social, proteção à maternidade e à infância e assistência aos desamparados. Os arts. 7º a 11 tratam do trabalhador (sindicato, greve, representante nas empresas com mais de 200 empregados).",
          "Saúde: para a OMS, é “completo bem-estar físico, mental e social”, conceito criticado mas importante por mostrar que saúde não é só ausência de doença. A seguridade social (art. 194) integra saúde, previdência e assistência. O art. 196 diz que a saúde é direito de todos e dever do Estado, com acesso universal e igualitário, sem exigir contrapartida. O SUS (art. 198; Lei 8.080/1990) segue as diretrizes de descentralização, atendimento integral com prioridade preventiva e participação da comunidade. O dever do Estado não exclui o das pessoas, das famílias, das empresas e da sociedade.",
          "Pela Lei 8.142/1990, o SUS tem a Conferência de Saúde (a cada quatro anos) e o Conselho de Saúde (permanente e deliberativo, com governo, prestadores, profissionais e usuários, sendo a representação dos usuários paritária).",
          "Educação (art. 205): direito de todos e dever do Estado e da família, com a colaboração da sociedade. O art. 206 traz os princípios: igualdade de acesso, liberdade de ensinar, pluralismo, gratuidade do ensino público, valorização dos profissionais, gestão democrática e padrão de qualidade. A LDB (Lei 9.394/1996) concretiza a gestão democrática por meio de conselhos escolares, e os conselhos municipais de educação, que não são obrigatórios, fiscalizam as políticas. A educação básica é obrigatória e gratuita dos 4 aos 17 anos, e o acesso ao ensino obrigatório é direito público subjetivo: os pais podem exigir a vaga na Justiça.",
          "Moradia: prevista no art. 6º e no art. 25 da DUDH. Não é só “um teto e quatro paredes”. A moradia adequada (FAU-USP) exige segurança da posse, serviços e infraestrutura, custo acessível, habitabilidade, não discriminação, localização adequada e adequação cultural. Conjuntos habitacionais isolados e sem infraestrutura não concretizam esse direito.",
        ],
        topicos: [
          "Cidadania ativa: participar de conselhos de saúde e de educação é também um dever do cidadão.",
          "O acesso universal à saúde, sem exigir contribuição prévia, não existe em todos os países.",
        ],
      },
      {
        titulo: "Proteção de grupos vulneráveis",
        paragrafos: [
          "Mulheres: o art. 226, § 8º, da CF obriga o Estado a criar mecanismos contra a violência nas relações familiares. A Lei Maria da Penha (Lei n. 11.340, de 7/8/2006) coíbe a violência doméstica e familiar contra a mulher, cria os Juizados de Violência Doméstica e permite medidas protetivas, como afastar o agressor do lar. O feminicídio foi tipificado em 2015 como crime hediondo. A central Ligue 180 recebe denúncias.",
          "Crianças e adolescentes: o art. 227 impõe à família, à sociedade e ao Estado assegurar seus direitos com absoluta prioridade. O ECA (Lei n. 8.069, de 13/7/1990) adota a proteção integral: criança é quem tem até 12 anos incompletos e adolescente quem tem entre 12 e 18 anos (excepcionalmente, aplica-se até os 21). A prioridade abrange primazia de socorro, precedência no atendimento, preferência nas políticas sociais e destinação privilegiada de recursos.",
          "Pessoas com deficiência: a CF proíbe discriminação salarial e de admissão (art. 7º, XXXI), garante benefício de um salário mínimo a quem não tem meios de subsistência (art. 203, V) e atendimento educacional especializado, preferencialmente na rede regular (art. 208, III). A Convenção da ONU (2006) foi promulgada pelo Decreto 6.949/2009. A Lei Brasileira de Inclusão (Estatuto da Pessoa com Deficiência, Lei n. 13.146/2015) define pessoa com deficiência como quem tem impedimento de longo prazo (físico, mental, intelectual ou sensorial) que, em interação com barreiras, pode obstruir sua participação plena na sociedade. A avaliação é biopsicossocial.",
          "Pessoa idosa: o Estatuto da Pessoa Idosa (Lei n. 10.741, de 1º/10/2003) protege pessoas com 60 anos ou mais, com absoluta prioridade e prioridade especial aos maiores de 80. Todo cidadão tem o dever de comunicar violações (art. 6º). O art. 230 da CF prevê que os programas de amparo sejam executados preferencialmente nos lares. A Resolução 46/1991 da ONU fixa os princípios de independência, participação, assistência, autorrealização e dignidade.",
          "População LGBTQIA+: o art. 3º, IV, da CF proíbe qualquer forma de discriminação. A OMS retirou a homossexualidade da lista de doenças em 17/5/1990. Por isso, o correto é “orientação sexual” (não “opção”) e “homossexualidade” (não “homossexualismo”). Os Princípios de Yogyakarta (2006, 29 princípios) aplicam o direito internacional dos direitos humanos à orientação sexual e à identidade de gênero.",
        ],
        topicos: [
          "Barreiras previstas na LBI: urbanísticas, arquitetônicas, nos transportes, nas comunicações, atitudinais e tecnológicas.",
          "A responsabilidade da sociedade com crianças e idosos é não prejudicar e não permitir que prejudiquem.",
        ],
      },
    ],
    pontosChave: [
      "As três teorias (jusnaturalista, positivista e moralista) são complementares.",
      "A dignidade da pessoa humana é fundamento da República (art. 1º, III, CF) e não exige contrapartida.",
      "Direitos humanos x fundamentais: diferença formal (tratados x positivados na Constituição).",
      "Dez características: universalidade, indivisibilidade, interdependência, imprescritibilidade, inalienabilidade, irrenunciabilidade, efetividade, inviolabilidade, complementaridade e vedação de retrocesso.",
      "Dimensões: 1ª liberdade (Magna Carta 1215) · 2ª igualdade (Revolução Industrial) · 3ª fraternidade (pós-guerra) · 4ª povos (democracia, pluralismo, genética) · 5ª paz.",
      "Haia 1899 → Liga das Nações e OIT 1919 → Nuremberg 1945/46 → ONU 1945 → DUDH 10/12/1948.",
      "Conselho de Segurança: único órgão da ONU com decisões obrigatórias; 5 membros permanentes com veto.",
      "Pactos de 1966 (civis e políticos / econômicos, sociais e culturais): o Brasil só aderiu em 1992.",
      "OEA em Bogotá (1948); Pacto de San José (1969; Brasil 1992); só a Comissão e os Estados levam casos à Corte.",
      "Caso Maria da Penha na CIDH (2001) → Lei 11.340/2006.",
      "Cláusulas pétreas (art. 60, § 4º): só uma nova Constituinte altera.",
      "O rol do art. 5º é exemplificativo.",
      "EC 45/2004: tratados com 3/5 em dois turnos = emenda constitucional; TPI; federalização (PGR → STJ).",
      "PNDH-1 (civis e políticos), PNDH-2 (sociais), PNDH-3 (seis eixos, incluindo Memória e Verdade).",
      "Direitos sociais: arts. 6º a 11. Saúde é direito de todos e dever do Estado (art. 196). A educação obrigatória é direito público subjetivo.",
      "ECA: criança até 12 anos incompletos. Idoso: 60 anos ou mais. LBI: deficiência = impedimento de longo prazo + barreiras.",
    ],
  },

  // ------------------------------------------------------------------
  // Quiz de fixação: 4 alternativas, "correta" é o índice da alternativa certa.
  quiz: [
    {
      pergunta: "Qual teoria afirma que os direitos humanos decorrem do simples fato de a pessoa ter nascido humana, existindo mesmo que nenhuma lei os proteja?",
      alternativas: ["Teoria positivista", "Teoria jusnaturalista", "Teoria moralista", "Teoria contratualista"],
      correta: 1,
      explicacao: "A teoria jusnaturalista fala em direitos naturais, universais e imutáveis, que existem independentemente de lei.",
    },
    {
      pergunta: "Quem foi o principal defensor da teoria moralista dos direitos humanos?",
      alternativas: ["Alexandre de Moraes", "Paulo Bonavides", "Charles Perelman", "Ingo Wolfgang Sarlet"],
      correta: 2,
      explicacao: "Charles Perelman, filósofo do Direito nascido em Varsóvia (1912–1984), é apontado como principal defensor da teoria moralista.",
    },
    {
      pergunta: "Qual característica impede que um Estado escolha proteger apenas alguns direitos humanos e deixe outros de lado?",
      alternativas: ["Imprescritibilidade", "Indivisibilidade", "Inalienabilidade", "Efetividade"],
      correta: 1,
      explicacao: "Indivisibilidade significa que o rol de direitos humanos forma um todo que não pode ser dividido.",
    },
    {
      pergunta: "O que significa a característica da vedação de retrocesso?",
      alternativas: [
        "Que ninguém perde um direito humano pelo passar do tempo",
        "Que os direitos humanos não podem ser vendidos nem doados",
        "Que um direito, uma vez reconhecido como direito humano, não pode ser retirado nem minimizado",
        "Que os direitos devem ser interpretados em conjunto",
      ],
      correta: 2,
      explicacao: "A vedação de retrocesso impede que um direito já integrado ao rol de direitos humanos seja retirado ou diminuído.",
    },
    {
      pergunta: "Por que a doutrina atual prefere a expressão “dimensões” a “gerações” de direitos humanos?",
      alternativas: [
        "Porque “gerações” só se aplica a direitos políticos",
        "Porque “dimensões” mostra que os direitos se somam e se complementam, sem que uma nova fase encerre a anterior",
        "Porque a ONU proibiu o uso da palavra “gerações”",
        "Porque “dimensões” indica que os direitos antigos foram substituídos",
      ],
      correta: 1,
      explicacao: "“Gerações” pode dar a falsa ideia de que a nova fase encerra a anterior. “Dimensões” transmite interação e complementaridade.",
    },
    {
      pergunta: "Qual documento é o marco simbólico da primeira dimensão de direitos humanos?",
      alternativas: [
        "A Constituição Mexicana de 1917",
        "A Declaração Universal dos Direitos Humanos de 1948",
        "A Magna Carta de 1215, do rei João Sem-Terra",
        "O Tratado de Versalhes de 1919",
      ],
      correta: 2,
      explicacao: "Com a Magna Carta (1215), João Sem-Terra se comprometeu a governar conforme as leis, limitando o poder do rei.",
    },
    {
      pergunta: "Os direitos de segunda dimensão (econômicos, sociais e culturais) são inspirados por qual ideal?",
      alternativas: ["Liberdade", "Igualdade", "Fraternidade", "Paz permanente"],
      correta: 1,
      explicacao: "Surgidos com a Revolução Industrial, os direitos de segunda dimensão buscam igualdade: salário justo, jornada limitada, saúde, educação etc.",
    },
    {
      pergunta: "O direito ao meio ambiente equilibrado e a proteção do consumidor pertencem a qual dimensão?",
      alternativas: ["Primeira", "Segunda", "Terceira", "Quinta"],
      correta: 2,
      explicacao: "São direitos difusos ou metaindividuais, de solidariedade ou fraternidade: terceira dimensão.",
    },
    {
      pergunta: "O direito à paz permanente, reforçado após atentados como o de 11 de setembro, é classificado como direito de:",
      alternativas: ["Segunda dimensão", "Terceira dimensão", "Quarta dimensão", "Quinta dimensão"],
      correta: 3,
      explicacao: "A quinta dimensão corresponde ao direito à paz permanente, defendido por Paulo Bonavides.",
    },
    {
      pergunta: "Qual organização é considerada a precursora da ONU?",
      alternativas: ["A Organização dos Estados Americanos", "A Liga das Nações", "A Organização Internacional do Trabalho", "O Conselho de Tutela"],
      correta: 1,
      explicacao: "A Liga das Nações foi criada em 1919, a partir do Tratado de Versalhes, e é a precursora da ONU.",
    },
    {
      pergunta: "O Tribunal de Nuremberg foi instituído para julgar quais categorias de crimes?",
      alternativas: [
        "Crimes contra a paz, crimes de guerra e crimes contra a humanidade",
        "Crimes políticos, eleitorais e financeiros",
        "Apenas crimes de genocídio",
        "Crimes cometidos pelos exércitos aliados",
      ],
      correta: 0,
      explicacao: "O Acordo de Londres (1945) definiu as três categorias: crimes contra a paz, crimes de guerra e crimes contra a humanidade.",
    },
    {
      pergunta: "Qual é o único órgão da ONU cujas decisões todos os membros devem aceitar e cumprir?",
      alternativas: ["Assembleia Geral", "Conselho de Segurança", "Conselho Econômico e Social", "Secretariado"],
      correta: 1,
      explicacao: "O Conselho de Segurança é o único com poder decisório. As resoluções da Assembleia Geral são apenas recomendações.",
    },
    {
      pergunta: "Quando foi adotada a Declaração Universal dos Direitos Humanos?",
      alternativas: ["24 de outubro de 1945", "10 de dezembro de 1948", "16 de dezembro de 1966", "22 de novembro de 1969"],
      correta: 1,
      explicacao: "A DUDH foi adotada em 10 de dezembro de 1948 por 48 Estados, com oito abstenções e nenhum voto contrário.",
    },
    {
      pergunta: "Por que a ONU criou dois pactos separados em 1966, em vez de um único pacto?",
      alternativas: [
        "Porque os EUA não aceitavam direitos políticos",
        "Por causa da Guerra Fria: a União Soviética se opunha ao direito de propriedade privada",
        "Porque o Brasil exigiu a separação",
        "Porque a DUDH já tratava de todos os direitos sociais",
      ],
      correta: 1,
      explicacao: "A disputa entre EUA e URSS, especialmente sobre direitos econômicos e propriedade privada, levou à criação de dois pactos.",
    },
    {
      pergunta: "A Convenção Americana de Direitos Humanos também é conhecida como:",
      alternativas: ["Protocolo de San Salvador", "Carta de Bogotá", "Pacto de San José da Costa Rica", "Estatuto de Roma"],
      correta: 2,
      explicacao: "Foi assinada em San José, na Costa Rica, em 1969, e entrou em vigor em 1978.",
    },
    {
      pergunta: "Quem pode submeter um caso à Corte Interamericana de Direitos Humanos?",
      alternativas: [
        "Qualquer vítima, diretamente",
        "Apenas a Comissão Interamericana e os Estados-partes",
        "Qualquer organização não governamental",
        "Somente a Assembleia Geral da ONU",
      ],
      correta: 1,
      explicacao: "O indivíduo não tem legitimidade para ir diretamente à Corte. Ele peticiona à Comissão, que pode levar o caso à Corte.",
    },
    {
      pergunta: "Pela EC n. 45/2004, os tratados de direitos humanos aprovados em dois turnos, por três quintos dos votos de cada Casa do Congresso, equivalem a:",
      alternativas: ["Leis ordinárias", "Decretos presidenciais", "Emendas constitucionais", "Leis complementares"],
      correta: 2,
      explicacao: "Com esse quórum, igual ao das emendas (art. 60, § 2º), o tratado passa a ter status constitucional.",
    },
    {
      pergunta: "Em quais artigos da Constituição Federal estão os direitos sociais?",
      alternativas: ["Arts. 1º a 4º", "Art. 5º", "Arts. 6º a 11", "Arts. 194 a 204"],
      correta: 2,
      explicacao: "Os direitos sociais estão no Capítulo II do Título II, arts. 6º a 11.",
    },
    {
      pergunta: "Para o Estatuto da Criança e do Adolescente, é considerada criança a pessoa:",
      alternativas: ["Até 12 anos de idade incompletos", "Até 14 anos de idade", "Até 16 anos de idade", "Até 18 anos de idade"],
      correta: 0,
      explicacao: "Criança tem até 12 anos incompletos; adolescente, entre 12 e 18 anos.",
    },
    {
      pergunta: "A partir de que idade uma pessoa é protegida pelo Estatuto da Pessoa Idosa?",
      alternativas: ["60 anos", "65 anos", "70 anos", "80 anos"],
      correta: 0,
      explicacao: "A Lei n. 10.741/2003 regula os direitos das pessoas com idade igual ou superior a 60 anos. Maiores de 80 têm prioridade especial.",
    },
  ],

  // ------------------------------------------------------------------
  flashcards: [
    { tema: "Teorias", frente: "Teoria jusnaturalista", verso: "Todo ser humano tem direitos naturais pelo simples fato de ter nascido humano. Existem mesmo sem lei; são universais e imutáveis." },
    { tema: "Teorias", frente: "Teoria positivista", verso: "São direitos humanos os escolhidos pelo povo e governantes e positivados em lei, por serem fundamentais à sociedade." },
    { tema: "Teorias", frente: "Teoria moralista", verso: "São direitos humanos os que se coadunam com a moral de cada sociedade. Principal defensor: Charles Perelman." },
    { tema: "Conceitos", frente: "Definição de direitos humanos (Alexandre de Moraes)", verso: "Conjunto institucionalizado de direitos e garantias do ser humano que visa respeitar sua dignidade, protegendo-o contra o arbítrio do Estado e garantindo condições mínimas de vida." },
    { tema: "Conceitos", frente: "Direitos humanos x direitos fundamentais", verso: "Diferença meramente formal: direitos humanos estão em tratados ou não positivados; direitos fundamentais estão positivados na constituição." },
    { tema: "Conceitos", frente: "Dignidade da pessoa humana na CF/88", verso: "É fundamento da República Federativa do Brasil (art. 1º, III). Vale para todos e não exige contrapartida." },
    { tema: "Características", frente: "Universalidade", verso: "Todos os seres humanos da Terra têm direito à proteção dos direitos humanos." },
    { tema: "Características", frente: "Indivisibilidade", verso: "O rol de direitos forma um todo: o Estado não pode escolher proteger alguns e deixar outros de lado." },
    { tema: "Características", frente: "Interdependência", verso: "Os direitos são inter-relacionados; não existe escala de importância entre eles." },
    { tema: "Características", frente: "Imprescritibilidade", verso: "Ninguém perde um direito humano pelo decurso do tempo." },
    { tema: "Características", frente: "Inalienabilidade", verso: "Direitos humanos não podem ser transferidos, negociados ou cedidos, seja a título gratuito ou oneroso." },
    { tema: "Características", frente: "Irrenunciabilidade", verso: "Ninguém pode renunciar aos direitos humanos (à vida, à liberdade etc.)." },
    { tema: "Características", frente: "Efetividade e inviolabilidade", verso: "Efetividade: o Estado deve agir para concretizar os direitos. Inviolabilidade: ninguém (Estado ou particular) pode desrespeitá-los." },
    { tema: "Características", frente: "Complementaridade e vedação de retrocesso", verso: "Complementaridade: interpretar os direitos em conjunto. Vedação de retrocesso: direito reconhecido não pode ser retirado nem diminuído." },
    { tema: "Dimensões", frente: "1ª dimensão", verso: "Direitos civis e políticos (liberdades públicas), contra o arbítrio do Estado. Magna Carta (1215), Bill of Rights (1689), Independência dos EUA (1776), Revolução Francesa (1789). Valor: liberdade." },
    { tema: "Dimensões", frente: "2ª dimensão", verso: "Direitos econômicos, sociais e culturais, surgidos com a Revolução Industrial. Constituição Mexicana (1917), Weimar (1919), OIT (1919). Valor: igualdade." },
    { tema: "Dimensões", frente: "3ª dimensão", verso: "Direitos de solidariedade/fraternidade, difusos ou metaindividuais: meio ambiente, consumidor, paz e autodeterminação dos povos. Pós-Segunda Guerra." },
    { tema: "Dimensões", frente: "4ª dimensão", verso: "Direitos dos povos diante da globalização: democracia, informação e pluralismo (Bonavides). Inclui proteção contra abusos da genética." },
    { tema: "Dimensões", frente: "5ª dimensão", verso: "Direito à paz permanente (Bonavides). Alguns incluem a proteção contra crimes na internet." },
    { tema: "História", frente: "Conferência de Haia (1899)", verso: "Buscou formas pacíficas de solução de conflitos e regras para a guerra, origem do Direito Humanitário." },
    { tema: "História", frente: "Liga das Nações", verso: "Criada em 1919 pelo Tratado de Versalhes; precursora da ONU; relativizou a soberania, prevendo sanções a quem violasse obrigações." },
    { tema: "História", frente: "OIT", verso: "Organização Internacional do Trabalho, criada em 1919 (Tratado de Versalhes). Missão: trabalho decente, com liberdade, equidade, segurança e dignidade." },
    { tema: "História", frente: "Tribunal de Nuremberg", verso: "1945–1946, criado pelo Acordo de Londres. Julgou crimes contra a paz, crimes de guerra e crimes contra a humanidade. Criticado como “tribunal dos vencedores”." },
    { tema: "ONU", frente: "Os seis órgãos principais da ONU", verso: "Assembleia Geral, Conselho de Segurança, Conselho Econômico e Social, Conselho de Tutela, Corte Internacional de Justiça e Secretariado." },
    { tema: "ONU", frente: "Conselho de Segurança", verso: "15 membros: 5 permanentes com veto (EUA, Rússia, Reino Unido, França, China) e 10 eleitos por 2 anos. Único órgão com decisões obrigatórias." },
    { tema: "ONU", frente: "Corte Internacional de Justiça", verso: "Sede em Haia; 15 juízes; somente países (nunca indivíduos) podem recorrer a ela." },
    { tema: "Tratados", frente: "Declaração Universal dos Direitos Humanos", verso: "10/12/1948; 30 artigos; 48 votos a favor, 8 abstenções, nenhum contra. Conjuga liberdade (direitos civis e políticos) e igualdade (direitos econômicos, sociais e culturais)." },
    { tema: "Tratados", frente: "Artigo I da DUDH", verso: "Todos os seres humanos nascem livres e iguais em dignidade e direitos e devem agir uns com os outros com espírito de fraternidade." },
    { tema: "Tratados", frente: "Pactos Internacionais de 1966", verso: "Pacto dos Direitos Civis e Políticos e Pacto dos Direitos Econômicos, Sociais e Culturais. Separados pela Guerra Fria. O Brasil aderiu em 1992." },
    { tema: "Tratados", frente: "Refugiado (Convenção de 1951)", verso: "Pessoa fora de seu país por fundado temor de perseguição por raça, religião, nacionalidade, grupo social ou opinião política. Diferente de migrante, que se desloca por escolha." },
    { tema: "Sistema Interamericano", frente: "OEA", verso: "Criada em 30/4/1948 na IX Conferência Internacional Americana, em Bogotá (Carta da OEA). 35 Estados. Pilares: democracia, direitos humanos, segurança e desenvolvimento." },
    { tema: "Sistema Interamericano", frente: "Comissão Interamericana (CIDH)", verso: "Criada em 1959 (Santiago), instalada em 1960. 7 membros, mandato de 4 anos. Examina petições individuais e busca solução amistosa." },
    { tema: "Sistema Interamericano", frente: "Pacto de San José da Costa Rica", verso: "Convenção Americana de Direitos Humanos: assinada em 1969, em vigor em 1978. O Brasil aderiu em 25/9/1992." },
    { tema: "Sistema Interamericano", frente: "Corte Interamericana", verso: "7 juízes; competência consultiva e contenciosa; decisões vinculantes. Só a Comissão e os Estados levam casos a ela. O Brasil a reconheceu em 1998." },
    { tema: "Sistema Interamericano", frente: "Requisitos da petição individual", verso: "Esgotamento dos recursos internos (salvo demora injustificada ou inexistência de processo) e ausência de outra pendência internacional sobre o mesmo fato." },
    { tema: "Sistema Interamericano", frente: "Caso Maria da Penha", verso: "Vítima de dupla tentativa de homicídio pelo marido (1983). Em 2001 a CIDH responsabilizou o Brasil por omissão e negligência, o que levou à Lei 11.340/2006." },
    { tema: "Constituição", frente: "Fundamentos da República (art. 1º)", verso: "Soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político." },
    { tema: "Constituição", frente: "Cláusulas pétreas (art. 60, § 4º)", verso: "Forma federativa; voto direto, secreto, universal e periódico; separação dos Poderes; direitos e garantias individuais. Só uma nova Constituinte pode alterá-las." },
    { tema: "Constituição", frente: "AI-5", verso: "Ato Institucional n. 5 (13/12/1968): suspendeu direitos políticos e as garantias de vitaliciedade, inamovibilidade e estabilidade dos magistrados." },
    { tema: "Constituição", frente: "Rol do art. 5º", verso: "Meramente exemplificativo: outros direitos decorrentes dos princípios constitucionais e de tratados também são protegidos." },
    { tema: "Constituição", frente: "Casa como asilo inviolável (art. 5º, XI)", verso: "Só se entra sem consentimento em flagrante delito, desastre, para prestar socorro ou, durante o dia, por determinação judicial." },
    { tema: "Acusados", frente: "Princípio da pessoalidade (art. 5º, XLV)", verso: "A pena não passa da pessoa do condenado; a reparação do dano pode alcançar os sucessores até o limite do patrimônio transferido." },
    { tema: "Acusados", frente: "Presunção de inocência (art. 5º, LVII)", verso: "Ninguém é considerado culpado até o trânsito em julgado da sentença penal condenatória." },
    { tema: "EC 45/2004", frente: "Três mudanças da EC 45/2004", verso: "1) Tratados de DH aprovados por 3/5 em dois turnos = emenda constitucional; 2) submissão ao Tribunal Penal Internacional; 3) federalização de graves violações de DH." },
    { tema: "EC 45/2004", frente: "Federalização de crimes contra direitos humanos", verso: "O Procurador-Geral da República suscita no STJ incidente de deslocamento de competência para a Justiça Federal. Primeiro caso: Dorothy Stang (negado)." },
    { tema: "PNDH", frente: "PNDH-1, 2 e 3", verso: "PNDH-1 (1996): direitos civis e políticos. PNDH-2 (2002): direitos econômicos, sociais, culturais e ambientais. PNDH-3 (2009): seis eixos, incluindo Direito à Memória e à Verdade." },
    { tema: "Direitos sociais", frente: "Direitos sociais do art. 6º", verso: "Educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência social, proteção à maternidade e à infância e assistência aos desamparados." },
    { tema: "Direitos sociais", frente: "Diretrizes do SUS (art. 198)", verso: "Descentralização com direção única em cada esfera; atendimento integral, com prioridade para a prevenção; participação da comunidade." },
    { tema: "Direitos sociais", frente: "Direito público subjetivo à educação", verso: "O acesso ao ensino obrigatório e gratuito pode ser exigido na Justiça: os pais podem obrigar o poder público a garantir a vaga." },
    { tema: "Grupos vulneráveis", frente: "ECA: criança e adolescente", verso: "Lei 8.069/1990. Criança: até 12 anos incompletos. Adolescente: 12 a 18 anos. Proteção integral e absoluta prioridade." },
    { tema: "Grupos vulneráveis", frente: "Pessoa com deficiência (LBI)", verso: "Quem tem impedimento de longo prazo (físico, mental, intelectual ou sensorial) que, em interação com barreiras, pode obstruir sua participação plena na sociedade. Lei 13.146/2015." },
    { tema: "Grupos vulneráveis", frente: "Estatuto da Pessoa Idosa", verso: "Lei 10.741/2003: pessoas com 60 anos ou mais, com absoluta prioridade; prioridade especial aos maiores de 80." },
    { tema: "Grupos vulneráveis", frente: "Lei Maria da Penha", verso: "Lei 11.340/2006: coíbe a violência doméstica e familiar contra a mulher, cria Juizados especializados e medidas protetivas." },
  ],

  // ------------------------------------------------------------------
  // Prova: banco de questões com 5 alternativas. A cada tentativa o app sorteia
  // "questoesPorTentativa" questões e embaralha a ordem das alternativas.
  prova: {
    titulo: "Prova de Direitos Humanos — Unidades I e II",
    questoesPorTentativa: 20,
    questoes: [
      {
        tema: "Teorias",
        enunciado: "Sobre as teorias jusnaturalista, positivista e moralista, o entendimento adotado no material, com base em Alexandre de Moraes, é que:",
        alternativas: [
          "A teoria positivista prevalece, pois só é direito o que está escrito em lei",
          "As três teorias se completam e devem coexistir",
          "A teoria jusnaturalista foi superada após a Segunda Guerra Mundial",
          "A teoria moralista é a única adotada pela Constituição de 1988",
          "As teorias são excludentes e o estudante deve escolher uma delas",
        ],
        correta: 1,
        explicacao: "A consciência social (moralista), baseada em valores universais (jusnaturalista), fornece o substrato para o legislador positivar direitos (positivista). As teorias são complementares.",
      },
      {
        tema: "Conceitos",
        enunciado: "A distinção entre direitos humanos e direitos fundamentais, segundo o material, é:",
        alternativas: [
          "Material: os direitos fundamentais são mais importantes",
          "Meramente formal: os direitos humanos estão em tratados ou ainda não positivados, e os fundamentais estão positivados na constituição",
          "Territorial: direitos humanos valem só no exterior",
          "Temporal: direitos fundamentais surgiram antes dos direitos humanos",
          "Inexistente: as expressões nunca podem ser usadas como sinônimos",
        ],
        correta: 1,
        explicacao: "O conteúdo é o mesmo; muda apenas a fonte formal (tratado internacional ou positivação constitucional).",
      },
      {
        tema: "Características",
        enunciado: "Uma pessoa assina um contrato em que “vende” sua liberdade em troca de dinheiro. Esse contrato contraria principalmente quais características dos direitos humanos?",
        alternativas: [
          "Universalidade e interdependência",
          "Imprescritibilidade e efetividade",
          "Inalienabilidade e irrenunciabilidade",
          "Complementaridade e vedação de retrocesso",
          "Indivisibilidade e inviolabilidade",
        ],
        correta: 2,
        explicacao: "Direitos humanos não podem ser negociados ou cedidos (inalienabilidade) nem renunciados pelo titular (irrenunciabilidade).",
      },
      {
        tema: "Dignidade",
        enunciado: "Na Constituição Federal de 1988, a dignidade da pessoa humana aparece como:",
        alternativas: [
          "Objetivo fundamental da República (art. 3º)",
          "Direito social previsto no art. 6º",
          "Fundamento da República Federativa do Brasil (art. 1º, III)",
          "Princípio aplicável apenas às relações internacionais",
          "Norma programática sem aplicação imediata",
        ],
        correta: 2,
        explicacao: "O art. 1º, III, coloca a dignidade como fundamento da República, ao lado da soberania, da cidadania, dos valores sociais do trabalho e da livre iniciativa e do pluralismo político.",
      },
      {
        tema: "Dignidade",
        enunciado: "Diante da frase popular “direitos humanos são direitos de bandidos”, o material sustenta que acusados e condenados também devem ter sua dignidade respeitada porque:",
        alternativas: [
          "A lei brasileira não prevê punição para crimes violentos",
          "A dignidade não exige contrapartida, e responder à violência com violência seria vingança, igualando a sociedade ao criminoso",
          "Os tratados internacionais proíbem a pena de prisão",
          "Os presos têm mais direitos do que os demais cidadãos",
          "A Constituição só protege quem ainda não foi julgado",
        ],
        correta: 1,
        explicacao: "A sociedade civilizada pune (privação da liberdade), mas não se vinga. A dignidade vale para todos, independentemente de conduta.",
      },
      {
        tema: "Dimensões",
        enunciado: "Com a Revolução Industrial surgiram reivindicações como salário justo, limitação da jornada, previdência e acesso à saúde e à educação. Esses direitos compõem a:",
        alternativas: [
          "Primeira dimensão, ligada ao ideal de liberdade",
          "Segunda dimensão, ligada ao ideal de igualdade",
          "Terceira dimensão, ligada ao ideal de fraternidade",
          "Quarta dimensão, ligada ao pluralismo",
          "Quinta dimensão, ligada à paz permanente",
        ],
        correta: 1,
        explicacao: "São direitos econômicos, sociais e culturais, de segunda dimensão, inspirados pela igualdade.",
      },
      {
        tema: "Dimensões",
        enunciado: "Qual foi a primeira constituição a atribuir aos direitos trabalhistas o caráter de direitos fundamentais do homem?",
        alternativas: [
          "Constituição dos Estados Unidos (1787)",
          "Constituição de Weimar (1919)",
          "Constituição Mexicana (1917)",
          "Constituição Francesa (1791)",
          "Constituição Brasileira (1988)",
        ],
        correta: 2,
        explicacao: "A Constituição Mexicana de 1917 foi a primeira. A de Weimar (1919) destacou-se depois pelos direitos trabalhistas e pela educação pública.",
      },
      {
        tema: "Dimensões",
        enunciado: "O pluralismo, apontado como direito de quarta dimensão, busca principalmente:",
        alternativas: [
          "Garantir que só os grupos mais numerosos tenham representação política",
          "Assegurar voz política a grupos vulneráveis que não conseguem se organizar para ter representantes",
          "Permitir que grupos econômicos comprem apoio de parlamentares",
          "Substituir a democracia representativa pela democracia direta",
          "Proibir a formação de partidos políticos",
        ],
        correta: 1,
        explicacao: "Minorias (mulheres, negros, pessoas com deficiência etc.) são chamadas assim por falta de representação, não por serem menos numerosas. O pluralismo quer dar voz a elas.",
      },
      {
        tema: "Dimensões",
        enunciado: "Segundo a Declaração Universal sobre o Genoma Humano e os Direitos Humanos (Unesco, 1997):",
        alternativas: [
          "O genoma humano pode ser livremente comercializado",
          "A clonagem humana é permitida para fins de pesquisa",
          "O genoma humano em seu estado natural não deve ser objeto de transações financeiras",
          "Pessoas podem ser selecionadas para empregos com base em características genéticas",
          "A pesquisa genética deve prevalecer sobre os direitos humanos quando buscar a cura de doenças",
        ],
        correta: 2,
        explicacao: "O art. 4º veda transações financeiras com o genoma natural. A declaração também proíbe a discriminação genética e a clonagem humana.",
      },
      {
        tema: "História",
        enunciado: "A Conferência Internacional de Paz realizada em Haia, em 1899, é importante porque:",
        alternativas: [
          "Criou a Organização das Nações Unidas",
          "Aprovou a Declaração Universal dos Direitos Humanos",
          "Buscou soluções pacíficas para conflitos e regras para os períodos de guerra, dando origem ao direito humanitário",
          "Instalou o Tribunal Penal Internacional",
          "Pôs fim à Primeira Guerra Mundial",
        ],
        correta: 2,
        explicacao: "A história dos direitos humanos começa com regras para a guerra: proteção de feridos, prisioneiros e civis (Direito Humanitário).",
      },
      {
        tema: "História",
        enunciado: "Uma das inovações da Liga das Nações (1919) foi:",
        alternativas: [
          "Criar o Conselho de Segurança com direito de veto",
          "Relativizar a soberania dos Estados, prevendo sanções econômicas e militares a quem violasse as obrigações assumidas",
          "Julgar os crimes cometidos pelos nazistas",
          "Aprovar os Pactos Internacionais de 1966",
          "Criar o sistema interamericano de direitos humanos",
        ],
        correta: 1,
        explicacao: "Com a Convenção da Liga das Nações, a soberania deixou de ser absoluta: quem descumprisse as obrigações poderia sofrer sanções dos demais Estados.",
      },
      {
        tema: "História",
        enunciado: "Qual é a principal crítica feita ao Tribunal de Nuremberg?",
        alternativas: [
          "Ter absolvido todos os acusados",
          "Ter sido um “tribunal dos vencedores contra os vencidos”, julgando só alemães e não os oficiais aliados",
          "Ter sido convocado pela Liga das Nações",
          "Ter aplicado apenas penas de multa",
          "Ter sido realizado antes do fim da guerra",
        ],
        correta: 1,
        explicacao: "Discutiu-se a parcialidade do tribunal, que julgou apenas alemães, com acusados já “pré-condenados” pela imprensa.",
      },
      {
        tema: "ONU",
        enunciado: "Sobre a composição do Conselho de Segurança da ONU, é correto afirmar:",
        alternativas: [
          "Tem 193 membros, todos com direito a voto igual",
          "Tem 15 membros: 5 permanentes com direito a veto e 10 não permanentes eleitos por dois anos",
          "Tem 7 juízes eleitos pela Assembleia Geral",
          "Tem 15 membros, todos permanentes",
          "É formado apenas pelos países fundadores da Liga das Nações",
        ],
        correta: 1,
        explicacao: "Os permanentes com veto são EUA, Rússia, Reino Unido, França e China.",
      },
      {
        tema: "ONU",
        enunciado: "Sobre a Corte Internacional de Justiça, é correto afirmar:",
        alternativas: [
          "Tem sede em Nova York e recebe petições de indivíduos",
          "Tem sede em Haia e somente países podem recorrer a ela",
          "É formada por sete juízes eleitos pela OEA",
          "Suas decisões são apenas recomendações",
          "Foi suspensa em 1994",
        ],
        correta: 1,
        explicacao: "A Corte fica em Haia, tem 15 juízes e só países (nunca indivíduos) podem pedir seus pareceres ou recorrer a ela.",
      },
      {
        tema: "ONU",
        enunciado: "O Conselho de Tutela da ONU suspendeu suas atividades em 1994 porque:",
        alternativas: [
          "Foi substituído pelo Conselho de Segurança",
          "Seus objetivos foram atingidos: os territórios tutelados alcançaram a independência, sendo Palau o último",
          "Os Estados Unidos vetaram seu funcionamento",
          "Foi declarado inconstitucional pela Corte Internacional de Justiça",
          "Perdeu seu orçamento após a Guerra Fria",
        ],
        correta: 1,
        explicacao: "Os territórios sob tutela, em sua maioria africanos, tornaram-se independentes. Palau foi o último.",
      },
      {
        tema: "DUDH",
        enunciado: "O artigo VI da DUDH garante a todo ser humano o direito de ser reconhecido como pessoa perante a lei. Essa previsão foi incluída porque:",
        alternativas: [
          "Animais e plantas passaram a ser sujeitos de direito",
          "Em vários momentos da história, grupos como os escravizados e os judeus no Holocausto tiveram negada a condição de sujeitos de direito",
          "Somente os cidadãos de países membros da ONU eram considerados pessoas",
          "A ONU quis definir a maioridade civil",
          "Era preciso regulamentar a nacionalidade",
        ],
        correta: 1,
        explicacao: "Retirar de alguém a condição de pessoa foi a justificativa para escravidão e extermínio. Daí o conceito jurídico de “pessoa humana”.",
      },
      {
        tema: "DUDH",
        enunciado: "Segundo o art. XIV da DUDH, o direito de asilo NÃO pode ser invocado quando:",
        alternativas: [
          "A pessoa é perseguida por suas opiniões políticas",
          "A perseguição for legitimamente motivada por crimes de direito comum ou por atos contrários aos princípios da ONU",
          "A pessoa não possuir passaporte",
          "O país de origem for membro da ONU",
          "A pessoa for perseguida por motivo religioso",
        ],
        correta: 1,
        explicacao: "Quem pratica crimes comuns (homicídio, estupro) ou atos contrários à ONU não pode se valer do asilo.",
      },
      {
        tema: "DUDH",
        enunciado: "A Declaração Universal dos Direitos Humanos divide os direitos em duas categorias, buscando conjugar dois valores. Quais?",
        alternativas: [
          "Paz e segurança",
          "Liberdade (direitos civis e políticos) e igualdade (direitos econômicos, sociais e culturais)",
          "Soberania e autodeterminação",
          "Fraternidade e solidariedade",
          "Propriedade e trabalho",
        ],
        correta: 1,
        explicacao: "Os direitos civis e políticos expressam a liberdade; os econômicos, sociais e culturais, a igualdade. Depois foram detalhados nos Pactos de 1966.",
      },
      {
        tema: "Tratados",
        enunciado: "Integra o “núcleo inderrogável” do Pacto Internacional dos Direitos Civis e Políticos, que não pode ser suspenso nem em situações excepcionais:",
        alternativas: [
          "O direito de greve",
          "O direito de propriedade",
          "A proibição da tortura e da escravidão",
          "O direito a férias remuneradas",
          "A liberdade de reunião",
        ],
        correta: 2,
        explicacao: "O núcleo inclui vida, proibição da tortura, da escravidão e da prisão por dívida contratual, garantias penais, personalidade jurídica e liberdade de pensamento, consciência e religião.",
      },
      {
        tema: "Tratados",
        enunciado: "A diferença entre refugiado e migrante é que:",
        alternativas: [
          "O refugiado busca melhores salários; o migrante foge de guerras",
          "O refugiado foge de fundado temor de perseguição (raça, religião, nacionalidade, grupo social ou opinião política); o migrante se desloca por escolha, buscando melhores condições",
          "Não há diferença jurídica entre eles",
          "O migrante sempre tem direito a asilo",
          "O refugiado é quem viaja a turismo e é surpreendido por uma guerra",
        ],
        correta: 1,
        explicacao: "A Convenção de 1951 define refugiado pelo temor de perseguição. Migrantes optam por mudar de país em busca de trabalho, estudo ou reunião familiar.",
      },
      {
        tema: "Tratados",
        enunciado: "O Dia Internacional pela Eliminação da Discriminação Racial (21 de março) foi escolhido para homenagear:",
        alternativas: [
          "A abolição da escravidão no Brasil",
          "As vítimas do Massacre de Sharpeville, na África do Sul, em 1960",
          "A assinatura da Declaração Universal dos Direitos Humanos",
          "O fim do apartheid, em 1994",
          "A marcha de Martin Luther King em Washington",
        ],
        correta: 1,
        explicacao: "Tropas dispararam contra cerca de 20 mil negros que protestavam pacificamente contra a Lei do Passe: 69 mortos e 186 feridos.",
      },
      {
        tema: "Sistema Interamericano",
        enunciado: "Para que uma petição individual seja aceita pela Comissão Interamericana de Direitos Humanos, em regra, é necessário:",
        alternativas: [
          "Que a vítima seja representada pela ONU",
          "O esgotamento dos recursos internos do país e a inexistência de outra pendência internacional sobre o mesmo fato",
          "Autorização prévia do Estado denunciado",
          "Que o caso já tenha sido julgado pela Corte Internacional de Justiça",
          "Que a vítima more em um país diferente daquele onde ocorreu a violação",
        ],
        correta: 1,
        explicacao: "O esgotamento dos recursos internos só é dispensado em caso de demora injustificada ou se a lei do país não previr processo para aquela violação.",
      },
      {
        tema: "Sistema Interamericano",
        enunciado: "No caso Maria da Penha, levado à Comissão Interamericana de Direitos Humanos:",
        alternativas: [
          "O Brasil foi absolvido por falta de provas",
          "Em 2001, a Comissão responsabilizou o Estado brasileiro por omissão, negligência e tolerância, o que resultou na criação da Lei n. 11.340/2006",
          "A vítima recorreu diretamente à Corte Internacional de Justiça",
          "O agressor foi julgado pelo Tribunal Penal Internacional",
          "A Comissão arquivou o caso por não esgotamento dos recursos internos",
        ],
        correta: 1,
        explicacao: "Mais de 15 anos após o crime, não havia decisão definitiva. A responsabilização do Brasil levou à Lei Maria da Penha.",
      },
      {
        tema: "Sistema Interamericano",
        enunciado: "O Brasil aderiu tardiamente aos Pactos da ONU de 1966 e à Convenção Americana de Direitos Humanos, apenas em 1992. O principal motivo foi:",
        alternativas: [
          "A falta de recursos econômicos",
          "O regime de ditadura militar, que vigorou de 1964 a 1985",
          "A oposição da OEA à entrada do Brasil",
          "A Guerra das Malvinas",
          "A demora na tradução dos textos para o português",
        ],
        correta: 1,
        explicacao: "Os tratados só foram reconhecidos após a redemocratização, quando o país retomou o respeito aos direitos civis e políticos.",
      },
      {
        tema: "Constituição",
        enunciado: "O AI-5 suspendeu as garantias de vitaliciedade, inamovibilidade e estabilidade. Essas garantias:",
        alternativas: [
          "Protegiam os militares contra processos judiciais",
          "Protegem o cargo de magistrado, para que o juiz decida com independência, mesmo contra interesses poderosos",
          "Eram privilégios pessoais de deputados federais",
          "Garantiam a permanência do presidente no cargo",
          "Protegiam os professores universitários contra demissões",
        ],
        correta: 1,
        explicacao: "São garantias do cargo, e não da pessoa: permitem ao juiz decidir sem medo de vingança ou transferência.",
      },
      {
        tema: "Constituição",
        enunciado: "Sobre as cláusulas pétreas da Constituição Federal (art. 60, § 4º), é correto afirmar:",
        alternativas: [
          "Podem ser alteradas por emenda aprovada por maioria simples",
          "São absolutamente imutáveis, em qualquer hipótese",
          "São de difícil modificação, podendo ser alteradas apenas por uma nova Assembleia Nacional Constituinte",
          "Podem ser alteradas por decreto presidencial em caso de urgência",
          "Incluem o direito à moradia e o direito ao lazer",
        ],
        correta: 2,
        explicacao: "Protegem a forma federativa, o voto direto, secreto, universal e periódico, a separação dos Poderes e os direitos e garantias individuais.",
      },
      {
        tema: "Direitos fundamentais",
        enunciado: "De acordo com o art. 5º, XI, da CF, a casa é asilo inviolável. É permitido entrar nela sem o consentimento do morador:",
        alternativas: [
          "A qualquer hora, desde que por policial fardado",
          "Durante a noite, por determinação judicial",
          "Em caso de flagrante delito, desastre, para prestar socorro ou, durante o dia, por determinação judicial",
          "Sempre que houver suspeita de crime, mesmo sem ordem judicial",
          "Apenas com autorização do síndico ou do proprietário do imóvel",
        ],
        correta: 2,
        explicacao: "A ordem judicial só autoriza a entrada durante o dia. Flagrante, desastre e socorro dispensam autorização a qualquer hora.",
      },
      {
        tema: "Direitos fundamentais",
        enunciado: "O rol de direitos fundamentais do art. 5º da Constituição Federal é:",
        alternativas: [
          "Taxativo: só existem os direitos ali listados",
          "Meramente exemplificativo: outros direitos decorrentes dos princípios constitucionais e de tratados também são protegidos",
          "Válido apenas para brasileiros natos",
          "Aplicável somente em tempo de guerra",
          "Revogável por lei ordinária",
        ],
        correta: 1,
        explicacao: "O § 2º do art. 5º estabelece que os direitos expressos não excluem outros decorrentes do regime, dos princípios e dos tratados.",
      },
      {
        tema: "Acusados",
        enunciado: "Um condenado por homicídio morre antes de cumprir a pena. De acordo com o art. 5º, XLV (princípio da pessoalidade):",
        alternativas: [
          "Seus filhos devem cumprir o restante da pena",
          "A pena não passa da pessoa do condenado, mas a obrigação de reparar o dano pode ser estendida aos sucessores até o limite do patrimônio transferido",
          "Os herdeiros perdem todo o patrimônio próprio",
          "A vítima perde o direito à indenização",
          "O Estado assume a pena e a cumpre simbolicamente",
        ],
        correta: 1,
        explicacao: "Ninguém cumpre pena por outra pessoa. A reparação civil, porém, pode alcançar a herança, até o valor recebido.",
      },
      {
        tema: "Acusados",
        enunciado: "O art. 5º, LVII, da Constituição estabelece que ninguém será considerado culpado:",
        alternativas: [
          "Até a conclusão do inquérito policial",
          "Até a sentença de primeira instância",
          "Até o trânsito em julgado de sentença penal condenatória",
          "Até a confissão do acusado",
          "Até o oferecimento da denúncia",
        ],
        correta: 2,
        explicacao: "O trânsito em julgado ocorre quando não cabem mais recursos. Isso evita prisões injustas que depois seriam revertidas.",
      },
      {
        tema: "EC 45/2004",
        enunciado: "A Emenda Constitucional n. 45/2004 trouxe três importantes mudanças para a proteção dos direitos humanos. Qual alternativa NÃO corresponde a uma delas?",
        alternativas: [
          "Tratados de direitos humanos aprovados por 3/5 em dois turnos passam a equivaler a emendas constitucionais",
          "O Brasil se submete à jurisdição do Tribunal Penal Internacional",
          "Possibilidade de federalização de graves violações de direitos humanos",
          "Criação da Comissão Interamericana de Direitos Humanos",
          "Possibilidade de tratados como a Convenção sobre os Direitos das Pessoas com Deficiência terem status de norma constitucional",
        ],
        correta: 3,
        explicacao: "A Comissão Interamericana foi criada em 1959, no âmbito da OEA. As outras três mudanças são da EC 45.",
      },
      {
        tema: "EC 45/2004",
        enunciado: "Na federalização de graves violações de direitos humanos, prevista na EC 45/2004:",
        alternativas: [
          "O Presidente da República transfere o caso para a Polícia Federal por decreto",
          "O Procurador-Geral da República pode suscitar, perante o STJ, incidente de deslocamento de competência para a Justiça Federal",
          "A vítima pode escolher entre a Justiça Estadual e a Federal",
          "O caso é enviado automaticamente à Corte Interamericana",
          "O STF julga diretamente todos os crimes contra direitos humanos",
        ],
        correta: 1,
        explicacao: "O pedido cabe ao PGR e é decidido pelo Superior Tribunal de Justiça, em qualquer fase do inquérito ou processo.",
      },
      {
        tema: "EC 45/2004",
        enunciado: "No primeiro pedido de federalização, referente ao assassinato da missionária Dorothy Stang (2005), o STJ:",
        alternativas: [
          "Aceitou o pedido e enviou o caso à Justiça Federal",
          "Negou o pedido, pois o Estado do Pará estava empenhado na apuração e a federalização deve ser exceção, atendendo à proporcionalidade",
          "Enviou o caso ao Tribunal Penal Internacional",
          "Declarou a EC 45 inconstitucional",
          "Arquivou o processo por falta de provas",
        ],
        correta: 1,
        explicacao: "O relator entendeu que não havia inércia ou negligência do Estado. A federalização é exceção, não regra.",
      },
      {
        tema: "PNDH",
        enunciado: "Qual dos eixos abaixo pertence ao Programa Nacional de Direitos Humanos 3 (PNDH-3)?",
        alternativas: [
          "Privatização dos Serviços Públicos",
          "Direito à Memória e à Verdade",
          "Redução da Maioridade Penal",
          "Extinção dos Conselhos Municipais",
          "Centralização das Políticas de Saúde",
        ],
        correta: 1,
        explicacao: "Os seis eixos do PNDH-3 incluem o Direito à Memória e à Verdade, voltado aos acontecimentos do regime militar.",
      },
      {
        tema: "PNDH",
        enunciado: "Os Programas Nacionais de Direitos Humanos tiveram focos diferentes. O PNDH-1 (1996) priorizou:",
        alternativas: [
          "Os direitos econômicos, sociais e culturais",
          "Os direitos civis e políticos (primeira dimensão)",
          "O direito à paz permanente",
          "Os direitos ambientais",
          "O direito à memória e à verdade",
        ],
        correta: 1,
        explicacao: "O PNDH-1 focou direitos civis e políticos; o PNDH-2, direitos econômicos, sociais, culturais e ambientais; o PNDH-3 organizou seis eixos.",
      },
      {
        tema: "Direitos sociais",
        enunciado: "Os pais de uma criança de 6 anos não encontram vaga na escola pública. Com base no art. 208, § 1º, da Constituição:",
        alternativas: [
          "Devem aguardar até que o município tenha recursos",
          "Podem exigir judicialmente a vaga, pois o acesso ao ensino obrigatório e gratuito é direito público subjetivo",
          "Nada podem fazer, pois a educação é dever exclusivo da família",
          "Devem matricular a criança em escola particular às próprias custas",
          "Só podem reclamar à Comissão Interamericana",
        ],
        correta: 1,
        explicacao: "Por ser direito público subjetivo, a vaga pode ser exigida no Poder Judiciário, independentemente da alegação de falta de recursos.",
      },
      {
        tema: "Direitos sociais",
        enunciado: "Segundo o conceito de moradia adequada apresentado no material (FAU-USP), o direito à moradia:",
        alternativas: [
          "Resume-se a garantir um teto e quatro paredes",
          "Exige segurança da posse, infraestrutura e serviços, custo acessível, habitabilidade, não discriminação, localização adequada e adequação cultural",
          "É garantido por conjuntos habitacionais em áreas afastadas, mesmo sem transporte",
          "Não está previsto na Constituição Federal",
          "Aplica-se apenas a proprietários de imóveis",
        ],
        correta: 1,
        explicacao: "Conjuntos isolados e sem infraestrutura segregaram a população e não concretizaram o direito à moradia digna.",
      },
      {
        tema: "Direitos sociais",
        enunciado: "Sobre o Conselho de Saúde previsto na Lei n. 8.142/1990, é correto afirmar:",
        alternativas: [
          "É formado apenas por médicos e reúne-se a cada quatro anos",
          "É órgão colegiado permanente e deliberativo, com representantes do governo, prestadores, profissionais e usuários, sendo a representação dos usuários paritária",
          "É um órgão consultivo sem poder de fiscalização",
          "Substitui o Poder Executivo na gestão do SUS",
          "É composto exclusivamente por representantes do governo federal",
        ],
        correta: 1,
        explicacao: "A Conferência de Saúde é que se reúne a cada quatro anos. O Conselho é permanente e permite que cidadãos fiscalizem a política de saúde.",
      },
      {
        tema: "Grupos vulneráveis",
        enunciado: "De acordo com a Lei Brasileira de Inclusão (Lei n. 13.146/2015), pessoa com deficiência é aquela que:",
        alternativas: [
          "Possui qualquer doença, ainda que passageira",
          "Tem impedimento de longo prazo de natureza física, mental, intelectual ou sensorial que, em interação com barreiras, pode obstruir sua participação plena na sociedade",
          "Recebe benefício previdenciário por invalidez",
          "Tem mais de 60 anos de idade",
          "Foi declarada incapaz por sentença judicial",
        ],
        correta: 1,
        explicacao: "O conceito combina o impedimento de longo prazo com as barreiras do ambiente. A avaliação é biopsicossocial.",
      },
      {
        tema: "Grupos vulneráveis",
        enunciado: "Sobre a proteção da população LGBTQIA+, assinale a alternativa correta segundo o material:",
        alternativas: [
          "O termo correto é “opção sexual”",
          "A homossexualidade é considerada doença pela OMS",
          "A OMS retirou a homossexualidade da lista de doenças em 1990; por isso o correto é falar em orientação sexual, e não em “homossexualismo”",
          "A Constituição permite discriminação por orientação sexual",
          "Os Princípios de Yogyakarta foram revogados pela ONU",
        ],
        correta: 2,
        explicacao: "O sufixo “ismo” conota patologia. Ninguém “opta” por ser heterossexual ou homossexual; por isso se usa “orientação sexual”.",
      },
      {
        tema: "Grupos vulneráveis",
        enunciado: "Segundo o Estatuto da Pessoa Idosa, entre as próprias pessoas idosas é assegurada prioridade especial:",
        alternativas: [
          "Aos maiores de 65 anos",
          "Aos maiores de 70 anos",
          "Aos maiores de 80 anos",
          "Às pessoas idosas com renda acima de dez salários mínimos",
          "Aos aposentados do serviço público",
        ],
        correta: 2,
        explicacao: "O § 2º do art. 3º assegura prioridade especial aos maiores de 80 anos.",
      },
    ],
  },
});
